// AUTO-GENERATED by gen_bf16_expe_poly4_tables.cpp -- do not edit.
// Coefficients for the degree-4 Horner BF16 exp(x) implementation.
//   coefficients : 5 x 16 = 80 bits
//   tail ROM     : 11 x 7 = 77 bits
//   total        : 157 bits
//
// Each Horner step maps to ONE DSP48E1: A = acc (25 b signed),
// B = f (17 b unsigned), C = coefficient pre-shifted into the product
// scale with the rounding constant folded in.

/* verilator lint_off DECLFILENAME */
package bf16_expe_poly4_pkg;
    localparam int LOG2E_FRAC_BITS = 23;
    localparam logic [23:0] LOG2E_Q = 24'hB8AA3B;
    localparam int FRAC_BITS   = 17;
    localparam int DEGREE      = 4;
    localparam int ACC_FRAC    = 22;
    localparam int ACC_W       = 25;
    localparam int COEF_W      = 16;
    localparam int COEF_FRAC   = 14;
    localparam int PROD_W      = 43;
    localparam int ROUND_SHIFT = 15;
    // Named CONST_MULT_W, not MULT_W: bf16_exp2_pkg already uses that name.
    localparam int CONST_MULT_W = 32;   // 8 x 24 constant multiply
    // Minimum alignment shift is LOG2E_FRAC_BITS + 7 - MAX_EXP - FRAC_BITS.
    localparam int ALIGNED_W   = 26;
    localparam int INT_W       = ALIGNED_W - FRAC_BITS;

    // Rounding constant folded into every DSP C port (free).
    localparam logic signed [PROD_W-1:0] STEP_ROUND = PROD_W'(65536);

    // Coefficients, ascending order, scaled by 2^COEF_FRAC.
    localparam logic signed [COEF_W-1:0] POLY_C0 = COEF_W'(32768);   // 2.000000000000
    localparam logic signed [COEF_W-1:0] POLY_C1 = COEF_W'(-22711);   // -1.386169433594
    localparam logic signed [COEF_W-1:0] POLY_C2 = COEF_W'(7850);   // 0.479125976562
    localparam logic signed [COEF_W-1:0] POLY_C3 = COEF_W'(-1751);   // -0.106872558594
    localparam logic signed [COEF_W-1:0] POLY_C4 = COEF_W'(228);   // 0.013916015625

    // Subnormal tail and flush-to-zero boundary.
    localparam int TAIL_EXP     = 6;
    localparam int TAIL_MANT_LO = 47;
    localparam int TAIL_MANT_HI = 57;
    localparam int ZERO_EXP     = 6;
    localparam int ZERO_MANT_LO = 58;
    localparam int PAYLOAD_BITS = 157;
endpackage : bf16_expe_poly4_pkg
/* verilator lint_on DECLFILENAME */

// Subnormal results for exponent 6, mantissa 47..57.
module bf16_expe_poly4_tail_rom #(parameter bit REGISTERED = 1'b1) (
    input  logic clk,
    input  logic pipe_en,
    input  logic [3:0] addr,
    output logic [6:0] data
);
    (* rom_style = "distributed" *) logic [6:0] rom [0:10];
    initial begin
        rom[  0] = 7'd109;
        rom[  1] = 7'd66;
        rom[  2] = 7'd40;
        rom[  3] = 7'd24;
        rom[  4] = 7'd15;
        rom[  5] = 7'd9;
        rom[  6] = 7'd5;
        rom[  7] = 7'd3;
        rom[  8] = 7'd2;
        rom[  9] = 7'd1;
        rom[ 10] = 7'd1;
    end
    generate
        if (REGISTERED) begin : gen_sync
            always_ff @(posedge clk) if (pipe_en) data <= rom[addr];
        end else begin : gen_async
            assign data = rom[addr];
        end
    endgenerate
endmodule : bf16_expe_poly4_tail_rom
