// AUTO-GENERATED by gen_bf16_expe_hybrid_tables.cpp
// Threshold decoder for sparse exponent bins [-9, -2].
module bf16_expe_sparse_decode #(parameter bit REGISTERED = 1'b1) (
    input logic clk, input logic rst_n, input logic pipe_en,
    input logic [2:0] exp_index, input logic [6:0] mantissa,
    output logic [15:0] data
);
    logic [15:0] data_comb;
    always_comb begin
        data_comb = 16'h3F80;
        unique case (exp_index)
            3'd0: begin
                data_comb = 16'h3F80;
                if (mantissa >= 7'd1) data_comb = 16'h3F7F;
            end
            3'd1: begin
                data_comb = 16'h3F7F;
                if (mantissa >= 7'd65) data_comb = 16'h3F7E;
            end
            3'd2: begin
                data_comb = 16'h3F7E;
                if (mantissa >= 7'd33) data_comb = 16'h3F7D;
                if (mantissa >= 7'd98) data_comb = 16'h3F7C;
            end
            3'd3: begin
                data_comb = 16'h3F7C;
                if (mantissa >= 7'd18) data_comb = 16'h3F7B;
                if (mantissa >= 7'd50) data_comb = 16'h3F7A;
                if (mantissa >= 7'd83) data_comb = 16'h3F79;
                if (mantissa >= 7'd116) data_comb = 16'h3F78;
            end
            3'd4: begin
                data_comb = 16'h3F78;
                if (mantissa >= 7'd11) data_comb = 16'h3F77;
                if (mantissa >= 7'd27) data_comb = 16'h3F76;
                if (mantissa >= 7'd44) data_comb = 16'h3F75;
                if (mantissa >= 7'd61) data_comb = 16'h3F74;
                if (mantissa >= 7'd78) data_comb = 16'h3F73;
                if (mantissa >= 7'd94) data_comb = 16'h3F72;
                if (mantissa >= 7'd111) data_comb = 16'h3F71;
            end
            3'd5: begin
                data_comb = 16'h3F70;
                if (mantissa >= 7'd9) data_comb = 16'h3F6F;
                if (mantissa >= 7'd18) data_comb = 16'h3F6E;
                if (mantissa >= 7'd26) data_comb = 16'h3F6D;
                if (mantissa >= 7'd35) data_comb = 16'h3F6C;
                if (mantissa >= 7'd43) data_comb = 16'h3F6B;
                if (mantissa >= 7'd52) data_comb = 16'h3F6A;
                if (mantissa >= 7'd61) data_comb = 16'h3F69;
                if (mantissa >= 7'd70) data_comb = 16'h3F68;
                if (mantissa >= 7'd79) data_comb = 16'h3F67;
                if (mantissa >= 7'd87) data_comb = 16'h3F66;
                if (mantissa >= 7'd96) data_comb = 16'h3F65;
                if (mantissa >= 7'd105) data_comb = 16'h3F64;
                if (mantissa >= 7'd114) data_comb = 16'h3F63;
                if (mantissa >= 7'd123) data_comb = 16'h3F62;
            end
            3'd6: begin
                data_comb = 16'h3F62;
                if (mantissa >= 7'd2) data_comb = 16'h3F61;
                if (mantissa >= 7'd7) data_comb = 16'h3F60;
                if (mantissa >= 7'd12) data_comb = 16'h3F5F;
                if (mantissa >= 7'd16) data_comb = 16'h3F5E;
                if (mantissa >= 7'd21) data_comb = 16'h3F5D;
                if (mantissa >= 7'd25) data_comb = 16'h3F5C;
                if (mantissa >= 7'd30) data_comb = 16'h3F5B;
                if (mantissa >= 7'd35) data_comb = 16'h3F5A;
                if (mantissa >= 7'd39) data_comb = 16'h3F59;
                if (mantissa >= 7'd44) data_comb = 16'h3F58;
                if (mantissa >= 7'd49) data_comb = 16'h3F57;
                if (mantissa >= 7'd54) data_comb = 16'h3F56;
                if (mantissa >= 7'd58) data_comb = 16'h3F55;
                if (mantissa >= 7'd63) data_comb = 16'h3F54;
                if (mantissa >= 7'd68) data_comb = 16'h3F53;
                if (mantissa >= 7'd73) data_comb = 16'h3F52;
                if (mantissa >= 7'd78) data_comb = 16'h3F51;
                if (mantissa >= 7'd83) data_comb = 16'h3F50;
                if (mantissa >= 7'd88) data_comb = 16'h3F4F;
                if (mantissa >= 7'd93) data_comb = 16'h3F4E;
                if (mantissa >= 7'd98) data_comb = 16'h3F4D;
                if (mantissa >= 7'd103) data_comb = 16'h3F4C;
                if (mantissa >= 7'd108) data_comb = 16'h3F4B;
                if (mantissa >= 7'd113) data_comb = 16'h3F4A;
                if (mantissa >= 7'd118) data_comb = 16'h3F49;
                if (mantissa >= 7'd123) data_comb = 16'h3F48;
            end
            3'd7: begin
                data_comb = 16'h3F47;
                if (mantissa >= 7'd3) data_comb = 16'h3F46;
                if (mantissa >= 7'd5) data_comb = 16'h3F45;
                if (mantissa >= 7'd8) data_comb = 16'h3F44;
                if (mantissa >= 7'd11) data_comb = 16'h3F43;
                if (mantissa >= 7'd13) data_comb = 16'h3F42;
                if (mantissa >= 7'd16) data_comb = 16'h3F41;
                if (mantissa >= 7'd18) data_comb = 16'h3F40;
                if (mantissa >= 7'd21) data_comb = 16'h3F3F;
                if (mantissa >= 7'd24) data_comb = 16'h3F3E;
                if (mantissa >= 7'd27) data_comb = 16'h3F3D;
                if (mantissa >= 7'd29) data_comb = 16'h3F3C;
                if (mantissa >= 7'd32) data_comb = 16'h3F3B;
                if (mantissa >= 7'd35) data_comb = 16'h3F3A;
                if (mantissa >= 7'd37) data_comb = 16'h3F39;
                if (mantissa >= 7'd40) data_comb = 16'h3F38;
                if (mantissa >= 7'd43) data_comb = 16'h3F37;
                if (mantissa >= 7'd46) data_comb = 16'h3F36;
                if (mantissa >= 7'd49) data_comb = 16'h3F35;
                if (mantissa >= 7'd51) data_comb = 16'h3F34;
                if (mantissa >= 7'd54) data_comb = 16'h3F33;
                if (mantissa >= 7'd57) data_comb = 16'h3F32;
                if (mantissa >= 7'd60) data_comb = 16'h3F31;
                if (mantissa >= 7'd63) data_comb = 16'h3F30;
                if (mantissa >= 7'd66) data_comb = 16'h3F2F;
                if (mantissa >= 7'd69) data_comb = 16'h3F2E;
                if (mantissa >= 7'd72) data_comb = 16'h3F2D;
                if (mantissa >= 7'd75) data_comb = 16'h3F2C;
                if (mantissa >= 7'd78) data_comb = 16'h3F2B;
                if (mantissa >= 7'd81) data_comb = 16'h3F2A;
                if (mantissa >= 7'd84) data_comb = 16'h3F29;
                if (mantissa >= 7'd87) data_comb = 16'h3F28;
                if (mantissa >= 7'd90) data_comb = 16'h3F27;
                if (mantissa >= 7'd93) data_comb = 16'h3F26;
                if (mantissa >= 7'd96) data_comb = 16'h3F25;
                if (mantissa >= 7'd99) data_comb = 16'h3F24;
                if (mantissa >= 7'd102) data_comb = 16'h3F23;
                if (mantissa >= 7'd105) data_comb = 16'h3F22;
                if (mantissa >= 7'd108) data_comb = 16'h3F21;
                if (mantissa >= 7'd112) data_comb = 16'h3F20;
                if (mantissa >= 7'd115) data_comb = 16'h3F1F;
                if (mantissa >= 7'd118) data_comb = 16'h3F1E;
                if (mantissa >= 7'd121) data_comb = 16'h3F1D;
                if (mantissa >= 7'd124) data_comb = 16'h3F1C;
            end
            default: data_comb = 16'h3F80;
        endcase
    end
    generate
        if (REGISTERED) begin : gen_reg
            always_ff @(posedge clk or negedge rst_n) begin
                if (!rst_n) data <= 16'h3F80;
                else if (pipe_en) data <= data_comb;
            end
        end else begin : gen_comb
            assign data = data_comb;
        end
    endgenerate
endmodule : bf16_expe_sparse_decode
