// AUTO-GENERATED by gen_bf16_expe_cut_tables.cpp -- do not edit.
// Tables for the cut-point ladder BF16 exp(x) implementation.
//   cut ROM  : 128 x 13 = 1664 bits
//   cand ROM : 256 x 4 = 1024 bits
//   tail ROM : 11 x 7 = 77 bits
//   total    : 2765 bits

package bf16_expe_cut_pkg;
    // Datapath geometry (mirrors bf16_expe_cut_table.hpp).
    localparam int LOG2E_FRAC_BITS = 23;
    localparam int LOG2E_W         = 24;
    localparam logic [23:0] LOG2E_Q = 24'hB8AA3B;  // round(log2(e) * 2**23)
    localparam int FRAC_BITS       = 16;
    localparam int CAND_INDEX_BITS = 8;
    localparam int PROD_W          = 32;  // 8 x 24
    // Minimum shift is LOG2E_FRAC_BITS + 7 - MAX_EXP - FRAC_BITS.
    localparam int ALIGNED_W       = 25;
    localparam int INT_W           = ALIGNED_W - FRAC_BITS;
    localparam int CUT_DEV_BITS    = 13;
    localparam int CAND_DEV_BITS   = 4;
    localparam int CUT_DEV_BIAS    = -5374;
    localparam int CAND_DEV_BIAS   = -12;
    localparam int CUT_W           = 18;  // signed, holds [-6k, 66k]

    // Subnormal tail and flush-to-zero boundary.
    localparam int TAIL_EXP        = 6;
    localparam int TAIL_MANT_LO    = 47;
    localparam int TAIL_MANT_HI    = 57;
    localparam int ZERO_EXP        = 6;
    localparam int ZERO_MANT_LO    = 58;

    localparam int PAYLOAD_BITS    = 2765;
endpackage : bf16_expe_cut_pkg

// Candidate mantissa deviation, addressed by the top 8 bits of f.
module bf16_expe_cut_cand_rom #(parameter bit REGISTERED = 1'b1) (
    input  logic clk,
    input  logic pipe_en,
    input  logic [7:0] addr,
    output logic [3:0] data
);
    (* rom_style = "distributed" *) logic [3:0] rom [0:255];
    initial begin
        rom[  0] = 4'd11;
        rom[  1] = 4'd11;
        rom[  2] = 4'd11;
        rom[  3] = 4'd10;
        rom[  4] = 4'd11;
        rom[  5] = 4'd10;
        rom[  6] = 4'd10;
        rom[  7] = 4'd10;
        rom[  8] = 4'd10;
        rom[  9] = 4'd9;
        rom[ 10] = 4'd10;
        rom[ 11] = 4'd9;
        rom[ 12] = 4'd9;
        rom[ 13] = 4'd8;
        rom[ 14] = 4'd9;
        rom[ 15] = 4'd8;
        rom[ 16] = 4'd9;
        rom[ 17] = 4'd8;
        rom[ 18] = 4'd8;
        rom[ 19] = 4'd8;
        rom[ 20] = 4'd8;
        rom[ 21] = 4'd7;
        rom[ 22] = 4'd8;
        rom[ 23] = 4'd7;
        rom[ 24] = 4'd7;
        rom[ 25] = 4'd7;
        rom[ 26] = 4'd7;
        rom[ 27] = 4'd6;
        rom[ 28] = 4'd7;
        rom[ 29] = 4'd6;
        rom[ 30] = 4'd6;
        rom[ 31] = 4'd6;
        rom[ 32] = 4'd6;
        rom[ 33] = 4'd5;
        rom[ 34] = 4'd6;
        rom[ 35] = 4'd5;
        rom[ 36] = 4'd6;
        rom[ 37] = 4'd5;
        rom[ 38] = 4'd5;
        rom[ 39] = 4'd5;
        rom[ 40] = 4'd5;
        rom[ 41] = 4'd4;
        rom[ 42] = 4'd5;
        rom[ 43] = 4'd4;
        rom[ 44] = 4'd5;
        rom[ 45] = 4'd4;
        rom[ 46] = 4'd4;
        rom[ 47] = 4'd4;
        rom[ 48] = 4'd4;
        rom[ 49] = 4'd4;
        rom[ 50] = 4'd4;
        rom[ 51] = 4'd3;
        rom[ 52] = 4'd4;
        rom[ 53] = 4'd3;
        rom[ 54] = 4'd4;
        rom[ 55] = 4'd3;
        rom[ 56] = 4'd3;
        rom[ 57] = 4'd3;
        rom[ 58] = 4'd3;
        rom[ 59] = 4'd3;
        rom[ 60] = 4'd3;
        rom[ 61] = 4'd3;
        rom[ 62] = 4'd3;
        rom[ 63] = 4'd2;
        rom[ 64] = 4'd3;
        rom[ 65] = 4'd2;
        rom[ 66] = 4'd3;
        rom[ 67] = 4'd2;
        rom[ 68] = 4'd2;
        rom[ 69] = 4'd2;
        rom[ 70] = 4'd2;
        rom[ 71] = 4'd2;
        rom[ 72] = 4'd2;
        rom[ 73] = 4'd2;
        rom[ 74] = 4'd2;
        rom[ 75] = 4'd1;
        rom[ 76] = 4'd2;
        rom[ 77] = 4'd1;
        rom[ 78] = 4'd2;
        rom[ 79] = 4'd1;
        rom[ 80] = 4'd2;
        rom[ 81] = 4'd1;
        rom[ 82] = 4'd2;
        rom[ 83] = 4'd1;
        rom[ 84] = 4'd1;
        rom[ 85] = 4'd1;
        rom[ 86] = 4'd1;
        rom[ 87] = 4'd1;
        rom[ 88] = 4'd1;
        rom[ 89] = 4'd1;
        rom[ 90] = 4'd1;
        rom[ 91] = 4'd1;
        rom[ 92] = 4'd1;
        rom[ 93] = 4'd1;
        rom[ 94] = 4'd1;
        rom[ 95] = 4'd0;
        rom[ 96] = 4'd1;
        rom[ 97] = 4'd0;
        rom[ 98] = 4'd1;
        rom[ 99] = 4'd0;
        rom[100] = 4'd1;
        rom[101] = 4'd0;
        rom[102] = 4'd1;
        rom[103] = 4'd0;
        rom[104] = 4'd1;
        rom[105] = 4'd0;
        rom[106] = 4'd1;
        rom[107] = 4'd0;
        rom[108] = 4'd1;
        rom[109] = 4'd0;
        rom[110] = 4'd1;
        rom[111] = 4'd0;
        rom[112] = 4'd1;
        rom[113] = 4'd0;
        rom[114] = 4'd1;
        rom[115] = 4'd0;
        rom[116] = 4'd1;
        rom[117] = 4'd0;
        rom[118] = 4'd1;
        rom[119] = 4'd0;
        rom[120] = 4'd1;
        rom[121] = 4'd0;
        rom[122] = 4'd1;
        rom[123] = 4'd0;
        rom[124] = 4'd1;
        rom[125] = 4'd0;
        rom[126] = 4'd1;
        rom[127] = 4'd0;
        rom[128] = 4'd1;
        rom[129] = 4'd0;
        rom[130] = 4'd1;
        rom[131] = 4'd0;
        rom[132] = 4'd1;
        rom[133] = 4'd0;
        rom[134] = 4'd1;
        rom[135] = 4'd0;
        rom[136] = 4'd1;
        rom[137] = 4'd0;
        rom[138] = 4'd1;
        rom[139] = 4'd0;
        rom[140] = 4'd1;
        rom[141] = 4'd0;
        rom[142] = 4'd1;
        rom[143] = 4'd0;
        rom[144] = 4'd1;
        rom[145] = 4'd0;
        rom[146] = 4'd1;
        rom[147] = 4'd0;
        rom[148] = 4'd1;
        rom[149] = 4'd1;
        rom[150] = 4'd1;
        rom[151] = 4'd1;
        rom[152] = 4'd1;
        rom[153] = 4'd1;
        rom[154] = 4'd1;
        rom[155] = 4'd1;
        rom[156] = 4'd1;
        rom[157] = 4'd1;
        rom[158] = 4'd2;
        rom[159] = 4'd1;
        rom[160] = 4'd2;
        rom[161] = 4'd1;
        rom[162] = 4'd2;
        rom[163] = 4'd1;
        rom[164] = 4'd2;
        rom[165] = 4'd1;
        rom[166] = 4'd2;
        rom[167] = 4'd1;
        rom[168] = 4'd2;
        rom[169] = 4'd2;
        rom[170] = 4'd2;
        rom[171] = 4'd2;
        rom[172] = 4'd2;
        rom[173] = 4'd2;
        rom[174] = 4'd3;
        rom[175] = 4'd2;
        rom[176] = 4'd3;
        rom[177] = 4'd2;
        rom[178] = 4'd3;
        rom[179] = 4'd2;
        rom[180] = 4'd3;
        rom[181] = 4'd2;
        rom[182] = 4'd3;
        rom[183] = 4'd3;
        rom[184] = 4'd3;
        rom[185] = 4'd3;
        rom[186] = 4'd3;
        rom[187] = 4'd3;
        rom[188] = 4'd3;
        rom[189] = 4'd3;
        rom[190] = 4'd4;
        rom[191] = 4'd3;
        rom[192] = 4'd4;
        rom[193] = 4'd3;
        rom[194] = 4'd4;
        rom[195] = 4'd4;
        rom[196] = 4'd4;
        rom[197] = 4'd4;
        rom[198] = 4'd5;
        rom[199] = 4'd4;
        rom[200] = 4'd5;
        rom[201] = 4'd4;
        rom[202] = 4'd5;
        rom[203] = 4'd4;
        rom[204] = 4'd5;
        rom[205] = 4'd5;
        rom[206] = 4'd5;
        rom[207] = 4'd5;
        rom[208] = 4'd5;
        rom[209] = 4'd5;
        rom[210] = 4'd6;
        rom[211] = 4'd5;
        rom[212] = 4'd6;
        rom[213] = 4'd6;
        rom[214] = 4'd6;
        rom[215] = 4'd6;
        rom[216] = 4'd6;
        rom[217] = 4'd6;
        rom[218] = 4'd7;
        rom[219] = 4'd6;
        rom[220] = 4'd7;
        rom[221] = 4'd7;
        rom[222] = 4'd7;
        rom[223] = 4'd7;
        rom[224] = 4'd7;
        rom[225] = 4'd7;
        rom[226] = 4'd7;
        rom[227] = 4'd7;
        rom[228] = 4'd8;
        rom[229] = 4'd7;
        rom[230] = 4'd8;
        rom[231] = 4'd8;
        rom[232] = 4'd8;
        rom[233] = 4'd8;
        rom[234] = 4'd9;
        rom[235] = 4'd8;
        rom[236] = 4'd9;
        rom[237] = 4'd9;
        rom[238] = 4'd9;
        rom[239] = 4'd9;
        rom[240] = 4'd9;
        rom[241] = 4'd9;
        rom[242] = 4'd10;
        rom[243] = 4'd9;
        rom[244] = 4'd10;
        rom[245] = 4'd10;
        rom[246] = 4'd10;
        rom[247] = 4'd10;
        rom[248] = 4'd10;
        rom[249] = 4'd10;
        rom[250] = 4'd11;
        rom[251] = 4'd10;
        rom[252] = 4'd11;
        rom[253] = 4'd11;
        rom[254] = 4'd11;
        rom[255] = 4'd11;
    end
    generate
        if (REGISTERED) begin : gen_sync
            always_ff @(posedge clk) if (pipe_en) data <= rom[addr];
        end else begin : gen_async
            assign data = rom[addr];
        end
    endgenerate
endmodule : bf16_expe_cut_cand_rom

// Cut-point deviation from the linear ladder, addressed by (k-1).
module bf16_expe_cut_cut_rom #(parameter bit REGISTERED = 1'b1) (
    input  logic clk,
    input  logic pipe_en,
    input  logic [6:0] addr,
    output logic [12:0] data
);
    (* rom_style = "distributed" *) logic [12:0] rom [0:127];
    initial begin
        rom[  0] = 13'd5555;
        rom[  1] = 13'd5329;
        rom[  2] = 13'd5102;
        rom[  3] = 13'd4875;
        rom[  4] = 13'd4729;
        rom[  5] = 13'd4587;
        rom[  6] = 13'd4360;
        rom[  7] = 13'd4129;
        rom[  8] = 13'd3907;
        rom[  9] = 13'd3800;
        rom[ 10] = 13'd3565;
        rom[ 11] = 13'd3471;
        rom[ 12] = 13'd3369;
        rom[ 13] = 13'd3110;
        rom[ 14] = 13'd2908;
        rom[ 15] = 13'd2850;
        rom[ 16] = 13'd2667;
        rom[ 17] = 13'd2521;
        rom[ 18] = 13'd2358;
        rom[ 19] = 13'd2228;
        rom[ 20] = 13'd2170;
        rom[ 21] = 13'd2068;
        rom[ 22] = 13'd1841;
        rom[ 23] = 13'd1751;
        rom[ 24] = 13'd1673;
        rom[ 25] = 13'd1527;
        rom[ 26] = 13'd1505;
        rom[ 27] = 13'd1322;
        rom[ 28] = 13'd1215;
        rom[ 29] = 13'd1154;
        rom[ 30] = 13'd1063;
        rom[ 31] = 13'd1094;
        rom[ 32] = 13'd911;
        rom[ 33] = 13'd817;
        rom[ 34] = 13'd759;
        rom[ 35] = 13'd737;
        rom[ 36] = 13'd699;
        rom[ 37] = 13'd657;
        rom[ 38] = 13'd511;
        rom[ 39] = 13'd489;
        rom[ 40] = 13'd387;
        rom[ 41] = 13'd360;
        rom[ 42] = 13'd447;
        rom[ 43] = 13'd241;
        rom[ 44] = 13'd219;
        rom[ 45] = 13'd197;
        rom[ 46] = 13'd175;
        rom[ 47] = 13'd120;
        rom[ 48] = 13'd131;
        rom[ 49] = 13'd109;
        rom[ 50] = 13'd87;
        rom[ 51] = 13'd33;
        rom[ 52] = 13'd28;
        rom[ 53] = 13'd22;
        rom[ 54] = 13'd128;
        rom[ 55] = 13'd17;
        rom[ 56] = 13'd44;
        rom[ 57] = 13'd2;
        rom[ 58] = 13'd0;
        rom[ 59] = 13'd103;
        rom[ 60] = 13'd61;
        rom[ 61] = 13'd59;
        rom[ 62] = 13'd37;
        rom[ 63] = 13'd51;
        rom[ 64] = 13'd78;
        rom[ 65] = 13'd96;
        rom[ 66] = 13'd129;
        rom[ 67] = 13'd176;
        rom[ 68] = 13'd194;
        rom[ 69] = 13'd237;
        rom[ 70] = 13'd380;
        rom[ 71] = 13'd338;
        rom[ 72] = 13'd352;
        rom[ 73] = 13'd366;
        rom[ 74] = 13'd489;
        rom[ 75] = 13'd466;
        rom[ 76] = 13'd513;
        rom[ 77] = 13'd640;
        rom[ 78] = 13'd638;
        rom[ 79] = 13'd696;
        rom[ 80] = 13'd718;
        rom[ 81] = 13'd841;
        rom[ 82] = 13'd879;
        rom[ 83] = 13'd942;
        rom[ 84] = 13'd992;
        rom[ 85] = 13'd1042;
        rom[ 86] = 13'd1185;
        rom[ 87] = 13'd1235;
        rom[ 88] = 13'd1282;
        rom[ 89] = 13'd1336;
        rom[ 90] = 13'd1406;
        rom[ 91] = 13'd1501;
        rom[ 92] = 13'd1567;
        rom[ 93] = 13'd1670;
        rom[ 94] = 13'd1772;
        rom[ 95] = 13'd1911;
        rom[ 96] = 13'd1925;
        rom[ 97] = 13'd2011;
        rom[ 98] = 13'd2112;
        rom[ 99] = 13'd2197;
        rom[100] = 13'd2299;
        rom[101] = 13'd2402;
        rom[102] = 13'd2498;
        rom[103] = 13'd2641;
        rom[104] = 13'd2737;
        rom[105] = 13'd2808;
        rom[106] = 13'd2930;
        rom[107] = 13'd3027;
        rom[108] = 13'd3170;
        rom[109] = 13'd3266;
        rom[110] = 13'd3364;
        rom[111] = 13'd3499;
        rom[112] = 13'd3602;
        rom[113] = 13'd3721;
        rom[114] = 13'd3841;
        rom[115] = 13'd3984;
        rom[116] = 13'd4103;
        rom[117] = 13'd4223;
        rom[118] = 13'd4342;
        rom[119] = 13'd4485;
        rom[120] = 13'd4605;
        rom[121] = 13'd4736;
        rom[122] = 13'd4867;
        rom[123] = 13'd5007;
        rom[124] = 13'd5141;
        rom[125] = 13'd5278;
        rom[126] = 13'd5417;
        rom[127] = 13'd5558;
    end
    generate
        if (REGISTERED) begin : gen_sync
            always_ff @(posedge clk) if (pipe_en) data <= rom[addr];
        end else begin : gen_async
            assign data = rom[addr];
        end
    endgenerate
endmodule : bf16_expe_cut_cut_rom

// Subnormal results for exponent 6, mantissa 47..57.
module bf16_expe_cut_tail_rom #(parameter bit REGISTERED = 1'b1) (
    input  logic clk,
    input  logic pipe_en,
    input  logic [3:0] addr,
    output logic [6:0] data
);
    (* rom_style = "distributed" *) logic [6:0] rom [0:10];
    initial begin
        rom[  0] = 7'd109;
        rom[  1] = 7'd66;
        rom[  2] = 7'd40;
        rom[  3] = 7'd24;
        rom[  4] = 7'd15;
        rom[  5] = 7'd9;
        rom[  6] = 7'd5;
        rom[  7] = 7'd3;
        rom[  8] = 7'd2;
        rom[  9] = 7'd1;
        rom[ 10] = 7'd1;
    end
    generate
        if (REGISTERED) begin : gen_sync
            always_ff @(posedge clk) if (pipe_en) data <= rom[addr];
        end else begin : gen_async
            assign data = rom[addr];
        end
    endgenerate
endmodule : bf16_expe_cut_tail_rom

