// =============================================================================
// bf16_exp2_optim_rom.sv
// 128-entry x 35-bit packed coefficient ROM for bf16_exp2_optim_approx.
//
// GENERATED by modeling/coeff_gen/gen_optim_coeffs.cpp. Do not edit.
// The same run also writes modeling/coeff_gen/bf16_exp2_optim_coeffs.hpp,
// so the RTL table and the C++ model table are the same numbers.
//
// Each entry stores two unsigned coefficients with no integer bit:
//   data[16:0]  = a  (slope,     Q0.17)
//   data[34:17] = b  (intercept, Q0.18)
//
// Neither coefficient ever reaches 1.0 over the whole BF16 input space
// (a in [0.347983, 0.690553], b in [0.847980, 0.999993]), which is what
// lets the integer bit of the shipped Q1.20 format be dropped:
//   128 x 42 b = 5376 b  ->  128 x 35 b = 4480 b
//
// Parameters:
//   REGISTERED - 1: synchronous output register (BRAM inference)
//                0: asynchronous / combinational (LUT ROM)
//
// IMPORTANT: when REGISTERED=1 the output is valid ONE clock cycle after
// addr. bf16_exp2_optim_approx accounts for this by delaying x identically.
// =============================================================================

module bf16_exp2_optim_rom #(
    parameter int DATA_W     = 35,
    parameter int DEPTH      = 128,
    parameter int ADDR_W     = 7,
    parameter bit REGISTERED = 1'b1
)(
    input  logic              clk,
    input  logic              pipe_en,
    input  logic [ADDR_W-1:0] addr,
    output logic [DATA_W-1:0] data
);
    (* rom_style = "block" *) logic [DATA_W-1:0] rom [0:DEPTH-1];

    initial begin
        rom[  0] = 35'h6c8aab22b;
        rom[  1] = 35'h6cc7eb323;
        rom[  2] = 35'h6d052b41c;
        rom[  3] = 35'h6d422b516;
        rom[  4] = 35'h6d7eeb612;
        rom[  5] = 35'h6dbbab70f;
        rom[  6] = 35'h6df82b80d;
        rom[  7] = 35'h6e348b90d;
        rom[  8] = 35'h6e70aba0e;
        rom[  9] = 35'h6eacabb11;
        rom[ 10] = 35'h6ee86bc15;
        rom[ 11] = 35'h6f240bd1a;
        rom[ 12] = 35'h6f5f8be21;
        rom[ 13] = 35'h6f9aabf2a;
        rom[ 14] = 35'h6fd5cc033;
        rom[ 15] = 35'h70108c13f;
        rom[ 16] = 35'h704b2c24b;
        rom[ 17] = 35'h7085ac359;
        rom[ 18] = 35'h70bfcc469;
        rom[ 19] = 35'h70f9cc57a;
        rom[ 20] = 35'h7133ac68c;
        rom[ 21] = 35'h716d2c7a0;
        rom[ 22] = 35'h71a66c8b6;
        rom[ 23] = 35'h71df8c9cd;
        rom[ 24] = 35'h72186cae5;
        rom[ 25] = 35'h72510cbff;
        rom[ 26] = 35'h72894cd1b;
        rom[ 27] = 35'h72c16ce38;
        rom[ 28] = 35'h72f94cf57;
        rom[ 29] = 35'h7330ed077;
        rom[ 30] = 35'h73682d199;
        rom[ 31] = 35'h739f4d2bc;
        rom[ 32] = 35'h73d60d3e1;
        rom[ 33] = 35'h740c8d507;
        rom[ 34] = 35'h7442cd630;
        rom[ 35] = 35'h7478ad759;
        rom[ 36] = 35'h74ae4d885;
        rom[ 37] = 35'h74e3ad9b2;
        rom[ 38] = 35'h7518cdae0;
        rom[ 39] = 35'h754d6dc10;
        rom[ 40] = 35'h7581edd42;
        rom[ 41] = 35'h75b60de76;
        rom[ 42] = 35'h75e9cdfab;
        rom[ 43] = 35'h761d4e0e2;
        rom[ 44] = 35'h76506e21b;
        rom[ 45] = 35'h76832e355;
        rom[ 46] = 35'h76b5ae491;
        rom[ 47] = 35'h76e7ce5cf;
        rom[ 48] = 35'h77198e70e;
        rom[ 49] = 35'h774aee84f;
        rom[ 50] = 35'h777bee992;
        rom[ 51] = 35'h77acaead7;
        rom[ 52] = 35'h77dceec1d;
        rom[ 53] = 35'h780cced66;
        rom[ 54] = 35'h783c6eeb0;
        rom[ 55] = 35'h786b8effb;
        rom[ 56] = 35'h789a4f149;
        rom[ 57] = 35'h78c88f298;
        rom[ 58] = 35'h78f68f3ea;
        rom[ 59] = 35'h79240f53d;
        rom[ 60] = 35'h79512f691;
        rom[ 61] = 35'h797def7e8;
        rom[ 62] = 35'h79aa2f941;
        rom[ 63] = 35'h79d5efa9b;
        rom[ 64] = 35'h79fbefbcc;
        rom[ 65] = 35'h7a26efd2a;
        rom[ 66] = 35'h7a516fe8a;
        rom[ 67] = 35'h7a7b8ffec;
        rom[ 68] = 35'h7aa510150;
        rom[ 69] = 35'h7ace302b5;
        rom[ 70] = 35'h7af6f041d;
        rom[ 71] = 35'h7b1f10586;
        rom[ 72] = 35'h7b46b06f2;
        rom[ 73] = 35'h7b6df085f;
        rom[ 74] = 35'h7b94909cf;
        rom[ 75] = 35'h7bbab0b40;
        rom[ 76] = 35'h7be050cb4;
        rom[ 77] = 35'h7c0570e29;
        rom[ 78] = 35'h7c2a10fa1;
        rom[ 79] = 35'h7c4e1111b;
        rom[ 80] = 35'h7c7191296;
        rom[ 81] = 35'h7c9491414;
        rom[ 82] = 35'h7cb6f1594;
        rom[ 83] = 35'h7cd8d1715;
        rom[ 84] = 35'h7cf9f1899;
        rom[ 85] = 35'h7d16919ef;
        rom[ 86] = 35'h7d32d1b45;
        rom[ 87] = 35'h7d5271ccf;
        rom[ 88] = 35'h7d7171e5b;
        rom[ 89] = 35'h7d8fd1fe9;
        rom[ 90] = 35'h7dadb2179;
        rom[ 91] = 35'h7dcad230c;
        rom[ 92] = 35'h7de7524a0;
        rom[ 93] = 35'h7e0352637;
        rom[ 94] = 35'h7e1e927d0;
        rom[ 95] = 35'h7e393296b;
        rom[ 96] = 35'h7e54b2b23;
        rom[ 97] = 35'h7e6df2cc2;
        rom[ 98] = 35'h7e8672e64;
        rom[ 99] = 35'h7e9e53009;
        rom[100] = 35'h7eb5731af;
        rom[101] = 35'h7ecbf3358;
        rom[102] = 35'h7ee1b3504;
        rom[103] = 35'h7ef6b36b1;
        rom[104] = 35'h7f0af3861;
        rom[105] = 35'h7f1e93a13;
        rom[106] = 35'h7f3033bac;
        rom[107] = 35'h7f4133d48;
        rom[108] = 35'h7f5293f01;
        rom[109] = 35'h7f63340bc;
        rom[110] = 35'h7f731427a;
        rom[111] = 35'h7f821443a;
        rom[112] = 35'h7f90f4612;
        rom[113] = 35'h7f9e347d0;
        rom[114] = 35'h7faad4998;
        rom[115] = 35'h7fb694b62;
        rom[116] = 35'h7fc194d2f;
        rom[117] = 35'h7fcb54eef;
        rom[118] = 35'h7fd4550b2;
        rom[119] = 35'h7fdcb5286;
        rom[120] = 35'h7fe49546f;
        rom[121] = 35'h7feb1563e;
        rom[122] = 35'h7ff0b5812;
        rom[123] = 35'h7ff5959e9;
        rom[124] = 35'h7ff995bda;
        rom[125] = 35'h7ffc95dad;
        rom[126] = 35'h7ffeb5f9d;
        rom[127] = 35'h7fffd6190;
    end

    generate
        if (REGISTERED) begin : gen_sync_rom
            always_ff @(posedge clk) begin
                if (pipe_en) data <= rom[addr];
            end
        end else begin : gen_async_rom
            assign data = rom[addr];
        end
    endgenerate

endmodule : bf16_exp2_optim_rom
