#ifndef BF16_EXP2_OPTIM_COEFFS_HPP
#define BF16_EXP2_OPTIM_COEFFS_HPP

/**
 * @file bf16_exp2_optim_coeffs.hpp
 * @brief Narrow coefficient ROM for the width-optimised exp2 core.
 *
 * GENERATED by modeling/coeff_gen/gen_optim_coeffs.cpp. Do not edit.
 *
 * Re-quantised from the shipped Q1.20 table. Both integer bits are
 * dropped because no coefficient ever reaches 1.0:
 *   a : Q1.20 -> Q0.17   b : Q1.20 -> Q0.18
 *   128 x 42 b = 5376 b  ->  128 x 35 b = 4480 b
 *
 * Packing matches the shipped table: b in the high field, a in the low.
 *   packed = (b << 17) | a
 */

#include <cstdint>

namespace bf16_exp2_optim_packed {

    /** @brief Number of piecewise-linear segments. */
    constexpr int LUT_SIZE = 128;

    /** @brief Slope coefficient format: unsigned Q0.17, strictly < 1. */
    constexpr int A_I = 0;
    constexpr int A_F = 17;
    constexpr int A_W = 17;

    /** @brief Offset coefficient format: unsigned Q0.18, strictly < 1. */
    constexpr int B_I = 0;
    constexpr int B_F = 18;
    constexpr int B_W = 18;

    /** @brief Width of one packed ROM word. */
    constexpr int PACKED_W = 35;

    /** @brief log2(e) constant, unchanged from the shipped table: Q1.22. */
    constexpr int LOG2E_I = 1;
    constexpr int LOG2E_F = 22;
    constexpr int LOG2E_W = 23;
    constexpr uint32_t log2e_int_val = 0x5c551d;

    /** @brief Packed coefficients: (b << 17) | a. */
    constexpr uint64_t coeffs[LUT_SIZE] = {
        0x6c8aab22bull, 0x6cc7eb323ull, 0x6d052b41cull, 0x6d422b516ull,
        0x6d7eeb612ull, 0x6dbbab70full, 0x6df82b80dull, 0x6e348b90dull,
        0x6e70aba0eull, 0x6eacabb11ull, 0x6ee86bc15ull, 0x6f240bd1aull,
        0x6f5f8be21ull, 0x6f9aabf2aull, 0x6fd5cc033ull, 0x70108c13full,
        0x704b2c24bull, 0x7085ac359ull, 0x70bfcc469ull, 0x70f9cc57aull,
        0x7133ac68cull, 0x716d2c7a0ull, 0x71a66c8b6ull, 0x71df8c9cdull,
        0x72186cae5ull, 0x72510cbffull, 0x72894cd1bull, 0x72c16ce38ull,
        0x72f94cf57ull, 0x7330ed077ull, 0x73682d199ull, 0x739f4d2bcull,
        0x73d60d3e1ull, 0x740c8d507ull, 0x7442cd630ull, 0x7478ad759ull,
        0x74ae4d885ull, 0x74e3ad9b2ull, 0x7518cdae0ull, 0x754d6dc10ull,
        0x7581edd42ull, 0x75b60de76ull, 0x75e9cdfabull, 0x761d4e0e2ull,
        0x76506e21bull, 0x76832e355ull, 0x76b5ae491ull, 0x76e7ce5cfull,
        0x77198e70eull, 0x774aee84full, 0x777bee992ull, 0x77acaead7ull,
        0x77dceec1dull, 0x780cced66ull, 0x783c6eeb0ull, 0x786b8effbull,
        0x789a4f149ull, 0x78c88f298ull, 0x78f68f3eaull, 0x79240f53dull,
        0x79512f691ull, 0x797def7e8ull, 0x79aa2f941ull, 0x79d5efa9bull,
        0x79fbefbccull, 0x7a26efd2aull, 0x7a516fe8aull, 0x7a7b8ffecull,
        0x7aa510150ull, 0x7ace302b5ull, 0x7af6f041dull, 0x7b1f10586ull,
        0x7b46b06f2ull, 0x7b6df085full, 0x7b94909cfull, 0x7bbab0b40ull,
        0x7be050cb4ull, 0x7c0570e29ull, 0x7c2a10fa1ull, 0x7c4e1111bull,
        0x7c7191296ull, 0x7c9491414ull, 0x7cb6f1594ull, 0x7cd8d1715ull,
        0x7cf9f1899ull, 0x7d16919efull, 0x7d32d1b45ull, 0x7d5271ccfull,
        0x7d7171e5bull, 0x7d8fd1fe9ull, 0x7dadb2179ull, 0x7dcad230cull,
        0x7de7524a0ull, 0x7e0352637ull, 0x7e1e927d0ull, 0x7e393296bull,
        0x7e54b2b23ull, 0x7e6df2cc2ull, 0x7e8672e64ull, 0x7e9e53009ull,
        0x7eb5731afull, 0x7ecbf3358ull, 0x7ee1b3504ull, 0x7ef6b36b1ull,
        0x7f0af3861ull, 0x7f1e93a13ull, 0x7f3033bacull, 0x7f4133d48ull,
        0x7f5293f01ull, 0x7f63340bcull, 0x7f731427aull, 0x7f821443aull,
        0x7f90f4612ull, 0x7f9e347d0ull, 0x7faad4998ull, 0x7fb694b62ull,
        0x7fc194d2full, 0x7fcb54eefull, 0x7fd4550b2ull, 0x7fdcb5286ull,
        0x7fe49546full, 0x7feb1563eull, 0x7ff0b5812ull, 0x7ff5959e9ull,
        0x7ff995bdaull, 0x7ffc95dadull, 0x7ffeb5f9dull, 0x7fffd6190ull
    };

} // namespace bf16_exp2_optim_packed

#endif // BF16_EXP2_OPTIM_COEFFS_HPP
