/**
 * @file gen_optim_coeffs.cpp
 * @brief Emits the narrow coefficient ROM for the width-optimised exp2 core,
 *        in both C++ and SystemVerilog form.
 *
 * Two outputs, one source of truth:
 *   modeling/coeff_gen/bf16_exp2_optim_coeffs.hpp  - the C++ model's table
 *   src/rtl/bf16_exp2_optim_rom.sv                 - the RTL's table
 *
 * They are written in the same pass from the same array, so the model and the
 * hardware cannot drift apart.
 *
 * The shipped table (bf16_exp2_packed_coeffs.hpp) stores both coefficients as
 * Q1.20. Two facts, both established exhaustively by tests/exp_pwl_optim.cpp,
 * let that be cut down:
 *
 *   - Neither coefficient ever reaches 1.0. Over every input pattern in both
 *     modes, a lands in [0.347983, 0.690553] and b in [0.847980, 0.999993].
 *     The integer bit of Q1.20 is therefore dead weight in every entry.
 *   - On the optimised datapath (log2e product 21 b, unified 21 b, x 17 b,
 *     accumulator 18 b) the fractional parts survive re-quantisation to
 *     a = Q0.17 and b = Q0.18 while the core stays bit-identical to
 *     bf16_exp2_approx<29>. One bit less on either coefficient breaks it.
 *
 * 42 b/entry -> 35 b/entry, 5376 b -> 4480 b of ROM.
 *
 * The rounding applied here is round-half-up. The table is a constant, so the
 * choice costs nothing in hardware; it only has to reproduce the values the
 * study verified.
 *
 * Build and run:  make gen_optim_coeffs
 */

#include <iostream>
#include <fstream>
#include <iomanip>
#include <cstdint>

#include "bf16_exp2_packed_coeffs.hpp"

namespace {

/** @brief Target fractional widths, as verified by tests/exp_pwl_optim.cpp. */
constexpr int A_F = 17;
constexpr int B_F = 18;
constexpr int A_W = A_F;   // no integer bit: a < 1 always
constexpr int B_W = B_F;   // no integer bit: b < 1 always
constexpr int PACKED_W = A_W + B_W;

/** @brief Re-quantise from @p from_f to @p to_f fractional bits, ties up. */
uint64_t requantise(uint64_t raw, int from_f, int to_f) {
    if (to_f >= from_f) return raw << (to_f - from_f);
    const int d = from_f - to_f;
    return (raw + (1ull << (d - 1))) >> d;
}

/** @brief Split one packed Q1.20 pair into its two raw integers. */
void unpack_shipped(int idx, uint64_t& a_raw, uint64_t& b_raw) {
    const uint64_t packed = bf16_exp2_packed::coeffs[idx].to_uint64();
    const uint64_t mask = (1ull << bf16_exp2_packed::COEFF_W) - 1;
    a_raw = packed & mask;
    b_raw = (packed >> bf16_exp2_packed::COEFF_W) & mask;
}

} // namespace

int main() {
    const char* out_path = "modeling/coeff_gen/bf16_exp2_optim_coeffs.hpp";
    std::ofstream out(out_path);
    if (!out) {
        std::cerr << "Cannot open " << out_path << " for writing.\n";
        return 1;
    }

    // --- Re-quantise and check the no-integer-bit claim on the way ---------
    uint64_t a_new[bf16_exp2_packed::LUT_SIZE];
    uint64_t b_new[bf16_exp2_packed::LUT_SIZE];
    uint64_t a_max = 0, b_max = 0;

    for (int i = 0; i < bf16_exp2_packed::LUT_SIZE; ++i) {
        uint64_t a20, b20;
        unpack_shipped(i, a20, b20);
        a_new[i] = requantise(a20, bf16_exp2_packed::COEFF_F, A_F);
        b_new[i] = requantise(b20, bf16_exp2_packed::COEFF_F, B_F);
        if (a_new[i] > a_max) a_max = a_new[i];
        if (b_new[i] > b_max) b_max = b_new[i];
    }

    // A coefficient rounding up to exactly 1.0 would need the integer bit back.
    if (a_max >= (1ull << A_W)) {
        std::cerr << "a overflows Q0." << A_F << " (max raw " << a_max << ").\n";
        return 1;
    }
    if (b_max >= (1ull << B_W)) {
        std::cerr << "b overflows Q0." << B_F << " (max raw " << b_max << ").\n";
        return 1;
    }

    // --- Emit -------------------------------------------------------------
    out << "#ifndef BF16_EXP2_OPTIM_COEFFS_HPP\n"
        << "#define BF16_EXP2_OPTIM_COEFFS_HPP\n\n"
        << "/**\n"
        << " * @file bf16_exp2_optim_coeffs.hpp\n"
        << " * @brief Narrow coefficient ROM for the width-optimised exp2 core.\n"
        << " *\n"
        << " * GENERATED by modeling/coeff_gen/gen_optim_coeffs.cpp. Do not edit.\n"
        << " *\n"
        << " * Re-quantised from the shipped Q1.20 table. Both integer bits are\n"
        << " * dropped because no coefficient ever reaches 1.0:\n"
        << " *   a : Q1.20 -> Q0." << A_F << "   b : Q1.20 -> Q0." << B_F << "\n"
        << " *   " << bf16_exp2_packed::LUT_SIZE << " x "
        << bf16_exp2_packed::PACKED_W << " b = "
        << (bf16_exp2_packed::LUT_SIZE * bf16_exp2_packed::PACKED_W) << " b  ->  "
        << bf16_exp2_packed::LUT_SIZE << " x " << PACKED_W << " b = "
        << (bf16_exp2_packed::LUT_SIZE * PACKED_W) << " b\n"
        << " *\n"
        << " * Packing matches the shipped table: b in the high field, a in the low.\n"
        << " *   packed = (b << " << A_W << ") | a\n"
        << " */\n\n"
        << "#include <cstdint>\n\n"
        << "namespace bf16_exp2_optim_packed {\n\n"
        << "    /** @brief Number of piecewise-linear segments. */\n"
        << "    constexpr int LUT_SIZE = " << bf16_exp2_packed::LUT_SIZE << ";\n\n"
        << "    /** @brief Slope coefficient format: unsigned Q0." << A_F << ", strictly < 1. */\n"
        << "    constexpr int A_I = 0;\n"
        << "    constexpr int A_F = " << A_F << ";\n"
        << "    constexpr int A_W = " << A_W << ";\n\n"
        << "    /** @brief Offset coefficient format: unsigned Q0." << B_F << ", strictly < 1. */\n"
        << "    constexpr int B_I = 0;\n"
        << "    constexpr int B_F = " << B_F << ";\n"
        << "    constexpr int B_W = " << B_W << ";\n\n"
        << "    /** @brief Width of one packed ROM word. */\n"
        << "    constexpr int PACKED_W = " << PACKED_W << ";\n\n"
        << "    /** @brief log2(e) constant, unchanged from the shipped table: Q"
        << bf16_exp2_packed::LOG2E_I << "." << bf16_exp2_packed::LOG2E_F << ". */\n"
        << "    constexpr int LOG2E_I = " << bf16_exp2_packed::LOG2E_I << ";\n"
        << "    constexpr int LOG2E_F = " << bf16_exp2_packed::LOG2E_F << ";\n"
        << "    constexpr int LOG2E_W = " << bf16_exp2_packed::LOG2E_W << ";\n"
        << "    constexpr uint32_t log2e_int_val = 0x"
        << std::hex << static_cast<uint32_t>(bf16_exp2_packed::log2e_int_val.to_uint())
        << std::dec << ";\n\n"
        << "    /** @brief Packed coefficients: (b << " << A_W << ") | a. */\n"
        << "    constexpr uint64_t coeffs[LUT_SIZE] = {\n";

    for (int i = 0; i < bf16_exp2_packed::LUT_SIZE; ++i) {
        const uint64_t packed = (b_new[i] << A_W) | a_new[i];
        if (i % 4 == 0) out << "        ";
        out << "0x" << std::hex << std::setw(9) << std::setfill('0') << packed
            << std::dec << std::setfill(' ') << "ull";
        if (i != bf16_exp2_packed::LUT_SIZE - 1) out << ",";
        out << ((i % 4 == 3) ? "\n" : " ");
    }

    out << "    };\n\n"
        << "} // namespace bf16_exp2_optim_packed\n\n"
        << "#endif // BF16_EXP2_OPTIM_COEFFS_HPP\n";

    out.close();

    // --- Emit the SystemVerilog ROM ---------------------------------------
    const char* sv_path = "src/rtl/bf16_exp2_optim_rom.sv";
    std::ofstream sv(sv_path);
    if (!sv) {
        std::cerr << "Cannot open " << sv_path << " for writing.\n";
        return 1;
    }

    const int nibbles = (PACKED_W + 3) / 4;

    sv << "// ============================================================================="
       << "\n// bf16_exp2_optim_rom.sv\n"
       << "// " << bf16_exp2_packed::LUT_SIZE << "-entry x " << PACKED_W
       << "-bit packed coefficient ROM for bf16_exp2_optim_approx.\n"
       << "//\n"
       << "// GENERATED by modeling/coeff_gen/gen_optim_coeffs.cpp. Do not edit.\n"
       << "// The same run also writes modeling/coeff_gen/bf16_exp2_optim_coeffs.hpp,\n"
       << "// so the RTL table and the C++ model table are the same numbers.\n"
       << "//\n"
       << "// Each entry stores two unsigned coefficients with no integer bit:\n"
       << "//   data[" << (A_W - 1) << ":0]  = a  (slope,     Q0." << A_F << ")\n"
       << "//   data[" << (PACKED_W - 1) << ":" << A_W << "] = b  (intercept, Q0." << B_F << ")\n"
       << "//\n"
       << "// Neither coefficient ever reaches 1.0 over the whole BF16 input space\n"
       << "// (a in [0.347983, 0.690553], b in [0.847980, 0.999993]), which is what\n"
       << "// lets the integer bit of the shipped Q1.20 format be dropped:\n"
       << "//   " << bf16_exp2_packed::LUT_SIZE << " x " << bf16_exp2_packed::PACKED_W
       << " b = " << (bf16_exp2_packed::LUT_SIZE * bf16_exp2_packed::PACKED_W)
       << " b  ->  " << bf16_exp2_packed::LUT_SIZE << " x " << PACKED_W
       << " b = " << (bf16_exp2_packed::LUT_SIZE * PACKED_W) << " b\n"
       << "//\n"
       << "// Parameters:\n"
       << "//   REGISTERED - 1: synchronous output register (BRAM inference)\n"
       << "//                0: asynchronous / combinational (LUT ROM)\n"
       << "//\n"
       << "// IMPORTANT: when REGISTERED=1 the output is valid ONE clock cycle after\n"
       << "// addr. bf16_exp2_optim_approx accounts for this by delaying x identically.\n"
       << "// ============================================================================="
       << "\n\n"
       << "module bf16_exp2_optim_rom #(\n"
       << "    parameter int DATA_W     = " << PACKED_W << ",\n"
       << "    parameter int DEPTH      = " << bf16_exp2_packed::LUT_SIZE << ",\n"
       << "    parameter int ADDR_W     = 7,\n"
       << "    parameter bit REGISTERED = 1'b1\n"
       << ")(\n"
       << "    input  logic              clk,\n"
       << "    input  logic              pipe_en,\n"
       << "    input  logic [ADDR_W-1:0] addr,\n"
       << "    output logic [DATA_W-1:0] data\n"
       << ");\n"
       << "    (* rom_style = \"block\" *) logic [DATA_W-1:0] rom [0:DEPTH-1];\n\n"
       << "    initial begin\n";

    for (int i = 0; i < bf16_exp2_packed::LUT_SIZE; ++i) {
        const uint64_t packed = (b_new[i] << A_W) | a_new[i];
        sv << "        rom[" << std::setw(3) << i << "] = " << PACKED_W << "'h"
           << std::hex << std::setw(nibbles) << std::setfill('0') << packed
           << std::dec << std::setfill(' ') << ";\n";
    }

    sv << "    end\n\n"
       << "    generate\n"
       << "        if (REGISTERED) begin : gen_sync_rom\n"
       << "            always_ff @(posedge clk) begin\n"
       << "                if (pipe_en) data <= rom[addr];\n"
       << "            end\n"
       << "        end else begin : gen_async_rom\n"
       << "            assign data = rom[addr];\n"
       << "        end\n"
       << "    endgenerate\n\n"
       << "endmodule : bf16_exp2_optim_rom\n";

    sv.close();

    std::cout << "Wrote " << out_path << "\n"
              << "Wrote " << sv_path << "\n"
              << "  entries   : " << bf16_exp2_packed::LUT_SIZE << "\n"
              << "  a format  : Q0." << A_F << "  max raw " << a_max
              << " / " << ((1ull << A_W) - 1) << "\n"
              << "  b format  : Q0." << B_F << "  max raw " << b_max
              << " / " << ((1ull << B_W) - 1) << "\n"
              << "  ROM       : " << (bf16_exp2_packed::LUT_SIZE * bf16_exp2_packed::PACKED_W)
              << " b -> " << (bf16_exp2_packed::LUT_SIZE * PACKED_W) << " b\n";
    return 0;
}
