// =============================================================================
// gen_bf16_expe_lut_rom.cpp
// Generates src/rtl/bf16_expe_lut_rom.sv from bf16_expe_lut_table.hpp.
//
// The ROM stores the full correctly-rounded (RNE) exp(x) BF16 outputs for every
// negative input whose unbiased exponent lies in [-9, 7]. The RTL top-level
// (bf16_expe_lut.sv) reads this ROM with address:
//     addr = (unbiased_exp - LUT_MIN_EXP) * LUT_MANT_COUNT + mantissa
//          = (unbiased_exp + 9) * 128 + mantissa
//
// Usage: ./gen_bf16_expe_lut_rom  (writes src/rtl/bf16_expe_lut_rom.sv)
// =============================================================================

#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>

#include "bf16_expe_lut_table.hpp"

int main() {
    using namespace bf16_expe_lut;

    const char* out_path = "src/rtl/bf16_expe_lut_rom.sv";
    std::ofstream ofs(out_path);
    if (!ofs) {
        std::cerr << "ERROR: cannot open " << out_path << " for writing\n";
        return 1;
    }

    const int DATA_W = 16;
    const int DEPTH  = LUT_SIZE;   // 2176
    const int ADDR_W = 12;         // $clog2(2176) = 12

    ofs << "// ===========================================================================\n";
    ofs << "// bf16_expe_lut_rom.sv  --  AUTO-GENERATED by gen_bf16_expe_lut_rom.cpp\n";
    ofs << "// " << DEPTH << "-entry x " << DATA_W << "-bit correctly-rounded (RNE) exp(x) BF16 table.\n";
    ofs << "//\n";
    ofs << "// Each entry stores a complete 16-bit BF16 output (sign bit always 0).\n";
    ofs << "// Address = (unbiased_exp - LUT_MIN_EXP) * LUT_MANT_COUNT + mantissa\n";
    ofs << "//         = (unbiased_exp + 9) * 128 + mantissa   (range [-9, 7]).\n";
    ofs << "//\n";
    ofs << "// Synthesis attribute (* rom_style = \"block\" *) hints Vivado to infer BRAM.\n";
    ofs << "// For Intel/Quartus use (* ramstyle = \"M20K\" *) instead.\n";
    ofs << "//\n";
    ofs << "// Parameters:\n";
    ofs << "//   REGISTERED - 1: synchronous output register (BRAM inference, 1-cycle latency)\n";
    ofs << "//                0: asynchronous / combinational (LUT ROM, 0-cycle latency)\n";
    ofs << "// ===========================================================================\n";
    ofs << "\n";
    ofs << "module bf16_expe_lut_rom #(\n";
    ofs << "    parameter int DATA_W     = " << DATA_W << ",\n";
    ofs << "    parameter int DEPTH      = " << DEPTH << ",\n";
    ofs << "    parameter int ADDR_W     = " << ADDR_W << ",\n";
    ofs << "    parameter bit REGISTERED = 1'b1\n";
    ofs << ")(\n";
    ofs << "    input  logic              clk,\n";
    ofs << "    input  logic              pipe_en,\n";
    ofs << "    input  logic [ADDR_W-1:0] addr,\n";
    ofs << "    output logic [DATA_W-1:0] data\n";
    ofs << ");\n";
    ofs << "    (* rom_style = \"block\" *) logic [DATA_W-1:0] rom [0:DEPTH-1];\n";
    ofs << "\n";
    ofs << "    // -----------------------------------------------------------------------\n";
    ofs << "    // Correctly-rounded exp(x) table (full BF16 outputs)\n";
    ofs << "    // Generated from bf16_expe_lut_table.hpp\n";
    ofs << "    // -----------------------------------------------------------------------\n";
    ofs << "    initial begin\n";

    for (int i = 0; i < DEPTH; i++) {
        ofs << "        rom[" << std::setw(4) << std::setfill(' ') << i << "] = 16'h"
            << std::hex << std::uppercase << std::setw(4) << std::setfill('0')
            << table[i] << std::dec << ";\n";
    }

    ofs << "    end\n";
    ofs << "\n";
    ofs << "    // -----------------------------------------------------------------------\n";
    ofs << "    // Read port\n";
    ofs << "    //   REGISTERED=1 : synchronous output  -> BRAM inference (1-cycle latency)\n";
    ofs << "    //   REGISTERED=0 : combinational output -> LUT ROM        (0-cycle latency)\n";
    ofs << "    // -----------------------------------------------------------------------\n";
    ofs << "    generate\n";
    ofs << "        if (REGISTERED) begin : gen_sync\n";
    ofs << "            always_ff @(posedge clk)\n";
    ofs << "                if (pipe_en) data <= rom[addr];\n";
    ofs << "        end else begin : gen_async\n";
    ofs << "            assign data = rom[addr];\n";
    ofs << "        end\n";
    ofs << "    endgenerate\n";
    ofs << "\n";
    ofs << "endmodule : bf16_expe_lut_rom\n";

    ofs.close();
    std::cout << "Generated " << out_path << " (" << DEPTH << " entries)\n";
    return 0;
}
