// =============================================================================
// gen_bf16_expe_hybrid_tables.cpp
// Generates the tables used by the hybrid compressed exp(x) implementation.
//
// Sparse exponent bins [-9, -2] are encoded as an initial BF16 output plus the
// mantissa thresholds at which that output decrements by one BF16 code. Dense
// bins [-1, 6] remain a direct 1024 x 16-bit ROM. Exponent 7 is always zero.
// =============================================================================

#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

#include "bf16_expe_lut_table.hpp"

namespace {
constexpr int SPARSE_MIN_EXP = -9;
constexpr int SPARSE_MAX_EXP = -2;
constexpr int DENSE_MIN_EXP = -1;
constexpr int DENSE_MAX_EXP = 6;
constexpr int MANT_COUNT = 128;

std::vector<uint8_t> thresholds_for_exp(int exp) {
    std::vector<uint8_t> result;
    const int base = (exp - bf16_expe_lut::LUT_MIN_EXP) * MANT_COUNT;
    uint16_t previous = bf16_expe_lut::table[base];

    for (int mantissa = 1; mantissa < MANT_COUNT; ++mantissa) {
        const uint16_t current = bf16_expe_lut::table[base + mantissa];
        if (current != previous) {
            if (current + 1 != previous) {
                std::cerr << "Non-unit output transition for exponent " << exp
                          << ", mantissa " << mantissa << '\n';
                std::exit(1);
            }
            result.push_back(static_cast<uint8_t>(mantissa));
            previous = current;
        }
    }
    return result;
}

void write_cpp_header(const std::vector<uint16_t>& bases,
                      const std::vector<uint16_t>& offsets,
                      const std::vector<uint8_t>& thresholds) {
    std::ofstream out("src/approximations/bf16_expe_hybrid_table.hpp");
    if (!out) {
        std::cerr << "Cannot create C++ hybrid table header\n";
        std::exit(1);
    }

    out << "// AUTO-GENERATED by gen_bf16_expe_hybrid_tables.cpp\n"
        << "#ifndef BF16_EXPE_HYBRID_TABLE_HPP\n"
        << "#define BF16_EXPE_HYBRID_TABLE_HPP\n\n"
        << "#include <cstdint>\n\n"
        << "namespace bf16_expe_hybrid {\n"
        << "constexpr int SPARSE_MIN_EXP = -9;\n"
        << "constexpr int SPARSE_MAX_EXP = -2;\n"
        << "constexpr int SPARSE_EXP_COUNT = 8;\n"
        << "constexpr int DENSE_MIN_EXP = -1;\n"
        << "constexpr int DENSE_MAX_EXP = 6;\n"
        << "constexpr int DENSE_EXP_COUNT = 8;\n"
        << "constexpr int MANT_COUNT = 128;\n"
        << "constexpr int DENSE_SIZE = 1024;\n"
        << "constexpr int THRESHOLD_COUNT = " << thresholds.size() << ";\n\n";

    out << "static const uint16_t sparse_base[SPARSE_EXP_COUNT] = {\n    ";
    for (std::size_t i = 0; i < bases.size(); ++i) {
        out << "0x" << std::hex << std::uppercase << std::setw(4)
            << std::setfill('0') << bases[i] << std::dec;
        out << (i + 1 == bases.size() ? "\n" : ", ");
    }
    out << "};\n\n";

    out << "static const uint16_t sparse_offset[SPARSE_EXP_COUNT + 1] = {\n    ";
    for (std::size_t i = 0; i < offsets.size(); ++i) {
        out << offsets[i] << (i + 1 == offsets.size() ? "\n" : ", ");
    }
    out << "};\n\n";

    out << "static const uint8_t sparse_threshold[THRESHOLD_COUNT] = {\n    ";
    for (std::size_t i = 0; i < thresholds.size(); ++i) {
        out << static_cast<unsigned>(thresholds[i]);
        if (i + 1 != thresholds.size()) out << ", ";
        if ((i + 1) % 16 == 0 && i + 1 != thresholds.size()) out << "\n    ";
    }
    out << "\n};\n\n";

    out << "static const uint16_t dense_table[DENSE_SIZE] = {\n";
    const int dense_start = (DENSE_MIN_EXP - bf16_expe_lut::LUT_MIN_EXP) * MANT_COUNT;
    for (int i = 0; i < 1024; ++i) {
        if (i % 8 == 0) out << "    ";
        out << "0x" << std::hex << std::uppercase << std::setw(4)
            << std::setfill('0') << bf16_expe_lut::table[dense_start + i] << std::dec;
        out << (i == 1023 ? "" : ", ");
        if (i % 8 == 7) out << '\n';
    }
    out << "};\n\n} // namespace bf16_expe_hybrid\n\n#endif\n";
}

void write_dense_rom() {
    std::ofstream out("src/rtl/bf16_expe_hybrid_rom.sv");
    if (!out) {
        std::cerr << "Cannot create dense SystemVerilog ROM\n";
        std::exit(1);
    }

    out << "// AUTO-GENERATED by gen_bf16_expe_hybrid_tables.cpp\n"
        << "// Dense exponent bins [-1, 6]: 1024 complete BF16 outputs.\n"
        << "module bf16_expe_hybrid_rom #(parameter bit REGISTERED = 1'b1) (\n"
        << "    input logic clk, input logic pipe_en, input logic [9:0] addr,\n"
        << "    output logic [15:0] data\n);\n"
        << "    (* rom_style = \"block\" *) logic [15:0] rom [0:1023];\n"
        << "    initial begin\n";

    const int dense_start = (DENSE_MIN_EXP - bf16_expe_lut::LUT_MIN_EXP) * MANT_COUNT;
    for (int i = 0; i < 1024; ++i) {
        out << "        rom[" << std::setw(4) << std::setfill(' ') << i << "] = 16'h"
            << std::hex << std::uppercase << std::setw(4) << std::setfill('0')
            << bf16_expe_lut::table[dense_start + i] << std::dec << ";\n";
    }

    out << "    end\n"
        << "    generate\n"
        << "        if (REGISTERED) begin : gen_sync\n"
        << "            always_ff @(posedge clk) if (pipe_en) data <= rom[addr];\n"
        << "        end else begin : gen_async\n"
        << "            assign data = rom[addr];\n"
        << "        end\n"
        << "    endgenerate\n"
        << "endmodule : bf16_expe_hybrid_rom\n";
}

void write_sparse_decoder(const std::vector<uint16_t>& bases,
                          const std::vector<std::vector<uint8_t>>& per_exp) {
    std::ofstream out("src/rtl/bf16_expe_sparse_decode.sv");
    if (!out) {
        std::cerr << "Cannot create sparse SystemVerilog decoder\n";
        std::exit(1);
    }

    out << "// AUTO-GENERATED by gen_bf16_expe_hybrid_tables.cpp\n"
        << "// Threshold decoder for sparse exponent bins [-9, -2].\n"
        << "module bf16_expe_sparse_decode #(parameter bit REGISTERED = 1'b1) (\n"
        << "    input logic clk, input logic rst_n, input logic pipe_en,\n"
        << "    input logic [2:0] exp_index, input logic [6:0] mantissa,\n"
        << "    output logic [15:0] data\n);\n"
        << "    logic [15:0] data_comb;\n"
        << "    always_comb begin\n"
        << "        data_comb = 16'h3F80;\n"
        << "        unique case (exp_index)\n";

    for (int eidx = 0; eidx < 8; ++eidx) {
        out << "            3'd" << eidx << ": begin\n"
            << "                data_comb = 16'h" << std::hex << std::uppercase
            << std::setw(4) << std::setfill('0') << bases[eidx] << std::dec << ";\n";
        for (std::size_t i = 0; i < per_exp[eidx].size(); ++i) {
            out << "                if (mantissa >= 7'd"
                << static_cast<unsigned>(per_exp[eidx][i]) << ") data_comb = 16'h"
                << std::hex << std::uppercase << std::setw(4) << std::setfill('0')
                << static_cast<uint16_t>(bases[eidx] - i - 1) << std::dec << ";\n";
        }
        out << "            end\n";
    }

    out << "            default: data_comb = 16'h3F80;\n"
        << "        endcase\n"
        << "    end\n"
        << "    generate\n"
        << "        if (REGISTERED) begin : gen_reg\n"
        << "            always_ff @(posedge clk or negedge rst_n) begin\n"
        << "                if (!rst_n) data <= 16'h3F80;\n"
        << "                else if (pipe_en) data <= data_comb;\n"
        << "            end\n"
        << "        end else begin : gen_comb\n"
        << "            assign data = data_comb;\n"
        << "        end\n"
        << "    endgenerate\n"
        << "endmodule : bf16_expe_sparse_decode\n";
}
} // namespace

int main() {
    std::vector<uint16_t> bases;
    std::vector<uint16_t> offsets{0};
    std::vector<uint8_t> thresholds;
    std::vector<std::vector<uint8_t>> per_exp;

    for (int exp = SPARSE_MIN_EXP; exp <= SPARSE_MAX_EXP; ++exp) {
        const int base_index = (exp - bf16_expe_lut::LUT_MIN_EXP) * MANT_COUNT;
        bases.push_back(bf16_expe_lut::table[base_index]);
        per_exp.push_back(thresholds_for_exp(exp));
        thresholds.insert(thresholds.end(), per_exp.back().begin(), per_exp.back().end());
        offsets.push_back(static_cast<uint16_t>(thresholds.size()));
    }

    write_cpp_header(bases, offsets, thresholds);
    write_dense_rom();
    write_sparse_decoder(bases, per_exp);

    std::cout << "Generated hybrid tables: dense=1024x16 bits, sparse="
              << thresholds.size() << "x7-bit thresholds + 8x16-bit bases\n";
    return 0;
}
