// =============================================================================
// gen_bf16_expe_lut.cpp
// Generates a FULL lookup table for exp(x) (base-e) covering every BF16 input
// whose unbiased exponent lies in [-9, 7] (negative inputs only, since the
// wrapper returns 1.0 for positive inputs).
//
// Each table entry is the correctly-rounded (Round-to-Nearest-Even) BF16
// representation of exp(x). Because the entries are correctly rounded, the
// resulting model is guaranteed to be <= 0.5 ULP by construction.
//
// Table layout (flat array):
//   index = (unbiased_exp - LUT_MIN_EXP) * 128 + mantissa
//   size  = (LUT_MAX_EXP - LUT_MIN_EXP + 1) * 128 = 17 * 128 = 2176
//
// Output: src/approximations/bf16_expe_lut_table.hpp
// =============================================================================

#include <iostream>
#include <fstream>
#include <iomanip>
#include <cstdint>
#include <cstring>
#include <cmath>
#include "fp_utils.hpp"

// Convert a double to BF16 using Round-to-Nearest-Even (via float32 top-16 bits).
static uint16_t double_to_bf16_rne(double d) {
    float f = static_cast<float>(d);
    uint32_t bits;
    std::memcpy(&bits, &f, sizeof(bits));

    // NaN: preserve and force quiet bit
    if ((bits & 0x7fffffffu) > 0x7f800000u) {
        return static_cast<uint16_t>((bits >> 16) | 0x0040u);
    }

    // Round-to-nearest-even: add 0x7fff + LSB-of-result before truncating.
    uint32_t lsb = (bits >> 16) & 1u;
    bits += 0x7fffu + lsb;
    return static_cast<uint16_t>(bits >> 16);
}

int main() {
    constexpr int LUT_MIN_EXP   = -9;
    constexpr int LUT_MAX_EXP   = 7;
    constexpr int LUT_EXP_COUNT = LUT_MAX_EXP - LUT_MIN_EXP + 1;  // 17
    constexpr int LUT_MANT_COUNT = 128;
    constexpr int LUT_SIZE      = LUT_EXP_COUNT * LUT_MANT_COUNT; // 2176

    const std::string out_path = "src/approximations/bf16_expe_lut_table.hpp";
    std::ofstream out(out_path);
    if (!out.is_open()) {
        std::cerr << "Error: cannot open " << out_path << " for writing.\n";
        return 1;
    }

    out << "// =============================================================================\n";
    out << "// bf16_expe_lut_table.hpp  --  AUTO-GENERATED by gen_bf16_expe_lut.cpp\n";
    out << "// Full correctly-rounded (RNE) exp(x) table for BF16, exponent range [-9, 7].\n";
    out << "// index = (unbiased_exp - LUT_MIN_EXP) * 128 + mantissa\n";
    out << "// =============================================================================\n";
    out << "#ifndef BF16_EXPE_LUT_TABLE_HPP\n";
    out << "#define BF16_EXPE_LUT_TABLE_HPP\n\n";
    out << "#include <cstdint>\n\n";
    out << "namespace bf16_expe_lut {\n\n";
    out << "    constexpr int LUT_MIN_EXP    = " << LUT_MIN_EXP   << ";\n";
    out << "    constexpr int LUT_MAX_EXP    = " << LUT_MAX_EXP   << ";\n";
    out << "    constexpr int LUT_EXP_COUNT  = " << LUT_EXP_COUNT << ";\n";
    out << "    constexpr int LUT_MANT_COUNT = " << LUT_MANT_COUNT << ";\n";
    out << "    constexpr int LUT_SIZE       = " << LUT_SIZE      << ";\n\n";
    out << "    // Flattened 16-bit BF16 outputs (sign bit is always 0).\n";
    out << "    static const uint16_t table[LUT_SIZE] = {\n";

    int written = 0;
    for (int e = LUT_MIN_EXP; e <= LUT_MAX_EXP; ++e) {
        for (int m = 0; m < LUT_MANT_COUNT; ++m) {
            // Build negative BF16 input: sign=1, biased_exp = e + 127, mantissa = m
            uint32_t biased_exp = static_cast<uint32_t>(e + 127);
            uint16_t raw_input  = static_cast<uint16_t>(
                (1u << 15) | (biased_exp << 7) | static_cast<uint32_t>(m));

            double x   = fp_to_double(raw_input, FPType::BF16);
            double ref = std::exp(x);
            uint16_t out_bf16 = double_to_bf16_rne(ref);

            if ((written % 8) == 0) out << "        ";
            out << "0x" << std::hex << std::uppercase << std::setw(4)
                << std::setfill('0') << out_bf16 << std::dec << std::nouppercase;
            if (written != LUT_SIZE - 1) out << ",";
            if ((written % 8) == 7 || written == LUT_SIZE - 1) out << "\n";
            else out << " ";
            ++written;
        }
    }

    out << "    };\n\n";
    out << "} // namespace bf16_expe_lut\n\n";
    out << "#endif // BF16_EXPE_LUT_TABLE_HPP\n";
    out.close();

    std::cout << "Generated " << out_path << " with " << LUT_SIZE << " entries.\n";
    return 0;
}
