// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vbf16_expe_equiv_top.h for the primary calling header

#ifndef VERILATED_VBF16_EXPE_EQUIV_TOP___024ROOT_H_
#define VERILATED_VBF16_EXPE_EQUIV_TOP___024ROOT_H_  // guard

#include "verilated.h"


class Vbf16_expe_equiv_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vbf16_expe_equiv_top___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(s_axis_tvalid,0,0);
        VL_OUT8(s_axis_tready,0,0);
        VL_IN8(m_axis_tready,0,0);
        VL_OUT8(o_exp2_tvalid,0,0);
        VL_OUT8(o_exp2_tready,0,0);
        VL_OUT8(o_exp2opt_tvalid,0,0);
        VL_OUT8(o_exp2opt_tready,0,0);
        VL_OUT8(o_lut_tvalid,0,0);
        VL_OUT8(o_lut_tready,0,0);
        VL_OUT8(o_hybrid_tvalid,0,0);
        VL_OUT8(o_hybrid_tready,0,0);
        VL_OUT8(o_cut_tvalid,0,0);
        VL_OUT8(o_cut_tready,0,0);
        VL_OUT8(o_poly4_tvalid,0,0);
        VL_OUT8(o_poly4_tready,0,0);
        VL_OUT8(o_poly4dsp_tvalid,0,0);
        VL_OUT8(o_poly4dsp_tready,0,0);
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s2_eo_code;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s3_base2;
        CData/*7:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s3_mant_src;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_decompose__DOT__hidden_bit_comb;
        CData/*7:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_log2e_mult__DOT__mant_src_d;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_log2e_mult__DOT__base2_d;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_round__DOT__is_sub;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_round__DOT__p1_is_sub;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_round__DOT__p2_is_sub;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s2_eo_code;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s3_base2;
        CData/*7:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s3_mant_src;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_decompose__DOT__hidden_bit_comb;
        CData/*7:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_log2e_mult__DOT__mant_src_d;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_log2e_mult__DOT__base2_d;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_round__DOT__is_sub;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_round__DOT__p1_is_sub;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_round__DOT__p2_is_sub;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__s2_eo_code;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__u_decompose__DOT__hidden_bit_comb;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s2_eo_code;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s2_route;
        CData/*2:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s2_sparse_exp_index;
        CData/*6:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s2_mantissa;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s3_eo_code;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s3_route;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_decompose__DOT__hidden_bit_comb;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s2_eo_code;
        CData/*4:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__fe_shift;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__fe_route;
        CData/*3:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__fe_tail_addr;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__fe_eo_code;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s2_route;
        CData/*3:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s2_tail_addr;
        CData/*3:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s3_cand_dev;
        CData/*6:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s3_tail_data;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s3_eo_code;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s3_route;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s4_cut_sentinel;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s4_eo_code;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s4_route;
        CData/*6:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s4_tail_data;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s5_below_cut;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s5_eo_code;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s5_route;
    };
    struct {
        CData/*6:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s5_tail_data;
        CData/*3:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__u_decompose__DOT__status_comb;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__u_decompose__DOT__hidden_bit_comb;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__s2_route;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__s2_eo;
        CData/*3:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__s2_tail_addr;
        CData/*4:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__gen_frontend_barrel__DOT__fe1_shift;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__gen_frontend_barrel__DOT__fe1_route;
        CData/*3:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__gen_frontend_barrel__DOT__fe1_tail;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__gen_frontend_barrel__DOT__fe1_eo;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__gen_fe2_reg__DOT__fe2_route;
        CData/*3:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__gen_fe2_reg__DOT__fe2_tail;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__gen_fe2_reg__DOT__fe2_eo;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__u_decompose__DOT__hidden_bit_comb;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__s2_route;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__s2_eo;
        CData/*3:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__s2_tail_addr;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_frontend_dsp__DOT__fe1_route;
        CData/*3:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_frontend_dsp__DOT__fe1_tail;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_frontend_dsp__DOT__fe1_eo;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_fe2_reg__DOT__fe2_route;
        CData/*3:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_fe2_reg__DOT__fe2_tail;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_fe2_reg__DOT__fe2_eo;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__u_decompose__DOT__hidden_bit_comb;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_exp2__DOT__exp_delay__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_exp2__DOT__exp_delay__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_exp2__DOT__exp_delay__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_exp2__DOT__exp_delay__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_exp2__DOT__exp_delay__v4;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_exp2__DOT__exp_delay__v5;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v0;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v0;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v0;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v1;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v1;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v1;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v2;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v2;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v2;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v3;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v3;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v3;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v4;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v4;
    };
    struct {
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v4;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v4;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v4;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v4;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v4;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v4;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v5;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v5;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v5;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v5;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v5;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v5;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v5;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v5;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v6;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v6;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v6;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v6;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v6;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v6;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v6;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v6;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v7;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v7;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v7;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v7;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v7;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v7;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v7;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v7;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v0;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v0;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v0;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v1;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v1;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v1;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v2;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v2;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v2;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v3;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v3;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v3;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v4;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v4;
    };
    struct {
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v4;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v4;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v4;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v4;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v4;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v4;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v5;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v5;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v5;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v5;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v5;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v5;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v5;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v5;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v6;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v6;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v6;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v6;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v6;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v6;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v6;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v6;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v7;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v7;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v7;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v7;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v7;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v7;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v7;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v7;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_n__0;
        CData/*0:0*/ __VactContinue;
        VL_IN16(s_axis_tdata,15,0);
        VL_OUT16(o_exp2_tdata,15,0);
        VL_OUT16(o_exp2opt_tdata,15,0);
        VL_OUT16(o_lut_tdata,15,0);
        VL_OUT16(o_hybrid_tdata,15,0);
        VL_OUT16(o_cut_tdata,15,0);
        VL_OUT16(o_poly4_tdata,15,0);
        VL_OUT16(o_poly4dsp_tdata,15,0);
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s4_int_part;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s6_poly_exp;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__bf16_out;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__gen_axi_pipelined__DOT__vld_sr;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_normalize__DOT__msb_idx_comb;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_normalize__DOT__msb_idx_s;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_round__DOT__final_exponent;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_round__DOT__shift_9;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_round__DOT__p1_final_exp;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_round__DOT__p1_shift;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_round__DOT__sum_m_ext;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_round__DOT__p2_m_ext;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_round__DOT__p2_base_exp;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_recompose__DOT__bf16_comb;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s4_int_part;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s6_poly_exp;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__bf16_out;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__gen_axi_pipelined__DOT__vld_sr;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_normalize__DOT__msb_idx_comb;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_normalize__DOT__msb_idx_s;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_round__DOT__final_exponent;
    };
    struct {
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_round__DOT__shift_9;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_round__DOT__p1_final_exp;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_round__DOT__p1_shift;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_round__DOT__sum_m_ext;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_round__DOT__p2_m_ext;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_round__DOT__p2_base_exp;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_recompose__DOT__bf16_comb;
        SData/*11:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__s2_addr;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__s3_rom_data;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__core_data;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__gen_axi_pipelined__DOT__vld_sr;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__1__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__2__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__3__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__4__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__5__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__6__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__7__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__8__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__9__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__10__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__11__KET____DOT__nxt;
        SData/*9:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s2_dense_addr;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s3_sparse_data;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s3_dense_data;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__core_data;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__gen_axi_pipelined__DOT__valid_sr;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_sparse__DOT__data_comb;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__1__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__2__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__3__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__4__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__5__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__6__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__7__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__8__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__9__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__10__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__11__KET____DOT__nxt;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s2_int_part;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s2_frac;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s3_int_part;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s3_frac;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__base_count;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s4_base_count;
        SData/*12:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s4_cut_dev;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s4_frac;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s4_int_part;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__ladder_count;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s5_base_count;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s5_int_part;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__core_data;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__gen_axi_pipelined__DOT__valid_sr;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__1__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__2__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__3__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__4__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__5__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__6__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__7__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__8__KET____DOT__nxt;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__s2_int_part;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__core_data;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__gen_axi_pipelined__DOT__valid_sr;
    };
    struct {
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__1__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__2__KET____DOT__nxt;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__s2_int_part;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__core_data;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_axi_pipelined__DOT__valid_sr;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_frontend_dsp__DOT__fe1_onehot;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__1__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__2__KET____DOT__nxt;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_exp2__DOT__exp_delay__v0;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_exp2__DOT__exp_delay__v2;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_exp2__DOT__exp_delay__v4;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v0;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v1;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v2;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v3;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v4;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v5;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v6;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v7;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v0;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v1;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v2;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v3;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v4;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v5;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v6;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v7;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s1_decomposed;
        IData/*30:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s3_mant_out;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s7_rounded_fp;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s8_final_fp;
        IData/*30:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_log2e_mult__DOT__mant_mult;
        IData/*30:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_log2e_mult__DOT__gen_rne_reg__DOT__mant_rne_q;
        IData/*20:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_lin_approx__DOT__coeff_b_stage;
        IData/*20:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_lin_approx__DOT__gen_split_mult__DOT__gen_merge_reg__DOT__coeff_b_d;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_round__DOT__rounded_comb;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s1_decomposed;
        IData/*30:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s3_mant_out;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s7_rounded_fp;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s8_final_fp;
        IData/*30:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_log2e_mult__DOT__mant_mult;
        IData/*30:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_log2e_mult__DOT__gen_rne_reg__DOT__mant_rne_q;
        IData/*31:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_unified_shift__DOT__gen_shift_dsp__DOT__hi_prod_s;
        IData/*20:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_lin_approx__DOT__coeff_b_stage;
        IData/*20:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_lin_approx__DOT__gen_split_mult__DOT__gen_merge_reg__DOT__coeff_b_d;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_round__DOT__rounded_comb;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__s1_decomposed;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s1_decomposed;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s1_decomposed;
        IData/*31:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__fe_prod;
        IData/*31:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT____VdfgTmp_h0f01a197__0;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__s1_decomposed;
        IData/*16:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__s2_frac;
        IData/*31:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__gen_frontend_barrel__DOT__fe1_prod;
        IData/*25:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__gen_fe2_reg__DOT__fe2_aligned;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT____Vcellout__gen_horner__BRA__0__KET____DOT__u_step__acc_out;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT____Vcellout__gen_horner__BRA__1__KET____DOT__u_step__acc_out;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT____Vcellout__gen_horner__BRA__2__KET____DOT__u_step__acc_out;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT____Vcellout__gen_horner__BRA__3__KET____DOT__u_step__acc_out;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__s1_decomposed;
        IData/*16:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__s2_frac;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_frontend_dsp__DOT__fe1_t7;
        IData/*25:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_fe2_reg__DOT__fe2_aligned;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT____Vcellout__gen_horner__BRA__0__KET____DOT__u_step__acc_out;
    };
    struct {
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT____Vcellout__gen_horner__BRA__1__KET____DOT__u_step__acc_out;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT____Vcellout__gen_horner__BRA__2__KET____DOT__u_step__acc_out;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT____Vcellout__gen_horner__BRA__3__KET____DOT__u_step__acc_out;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v0;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v1;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v2;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v3;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v4;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v5;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v6;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v7;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v0;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v1;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v2;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v3;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v4;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v5;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v6;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v7;
        IData/*31:0*/ __VactIterCount;
        QData/*37:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s4_frac_part;
        QData/*61:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s5_unnorm_res;
        QData/*58:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s6_norm_mant;
        QData/*46:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_unified_shift__DOT__unified_shifted;
        QData/*41:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_lin_approx__DOT__packed_coeff;
        QData/*37:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_lin_approx__DOT__frac_aligned;
        QData/*61:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_lin_approx__DOT__calc_res;
        QData/*58:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_lin_approx__DOT__gen_split_mult__DOT__merged;
        QData/*58:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_lin_approx__DOT__gen_split_mult__DOT__gen_merge_reg__DOT__merged_q;
        QData/*61:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_normalize__DOT__res_s;
        QData/*58:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_normalize__DOT__poly_mant_comb;
        QData/*58:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_round__DOT__p1_mant;
        QData/*37:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s4_frac_part;
        QData/*61:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s5_unnorm_res;
        QData/*58:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s6_norm_mant;
        QData/*46:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_unified_shift__DOT__unified_shifted;
        QData/*32:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_unified_shift__DOT__gen_shift_dsp__DOT__lo_prod_s;
        QData/*41:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_lin_approx__DOT__packed_coeff;
        QData/*37:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_lin_approx__DOT__frac_aligned;
        QData/*61:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_lin_approx__DOT__calc_res;
        QData/*50:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_lin_approx__DOT__gen_split_mult__DOT__merged;
        QData/*50:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_lin_approx__DOT__gen_split_mult__DOT__gen_merge_reg__DOT__merged_q;
        QData/*61:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_normalize__DOT__res_s;
        QData/*58:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_normalize__DOT__poly_mant_comb;
        QData/*58:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_round__DOT__p1_mant;
        QData/*42:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__gen_horner__BRA__0__KET____DOT__u_step__DOT__mult_r;
        QData/*42:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__gen_horner__BRA__1__KET____DOT__u_step__DOT__mult_r;
        QData/*42:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__gen_horner__BRA__2__KET____DOT__u_step__DOT__mult_r;
        QData/*42:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__gen_horner__BRA__3__KET____DOT__u_step__DOT__mult_r;
        QData/*42:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_horner__BRA__0__KET____DOT__u_step__DOT__mult_r;
        QData/*42:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_horner__BRA__1__KET____DOT__u_step__DOT__mult_r;
        QData/*42:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_horner__BRA__2__KET____DOT__u_step__DOT__mult_r;
        QData/*42:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_horner__BRA__3__KET____DOT__u_step__DOT__mult_r;
        VlUnpacked<SData/*8:0*/, 4> bf16_expe_equiv_top__DOT__u_exp2__DOT__exp_delay;
        VlUnpacked<SData/*8:0*/, 7> bf16_expe_equiv_top__DOT__u_exp2__DOT__int_delay;
        VlUnpacked<CData/*1:0*/, 14> bf16_expe_equiv_top__DOT__u_exp2__DOT__eo_delay;
        VlUnpacked<QData/*35:0*/, 3> bf16_expe_equiv_top__DOT__u_exp2__DOT__u_lin_approx__DOT__gen_split_mult__DOT__part_comb;
        VlUnpacked<QData/*35:0*/, 3> bf16_expe_equiv_top__DOT__u_exp2__DOT__u_lin_approx__DOT__gen_split_mult__DOT__part_reg;
        VlUnpacked<QData/*41:0*/, 128> bf16_expe_equiv_top__DOT__u_exp2__DOT__u_lin_approx__DOT__u_coeff_rom__DOT__rom;
        VlUnpacked<SData/*8:0*/, 4> bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__exp_delay;
        VlUnpacked<SData/*8:0*/, 7> bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__int_delay;
        VlUnpacked<CData/*1:0*/, 14> bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__eo_delay;
        VlUnpacked<QData/*35:0*/, 2> bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_lin_approx__DOT__gen_split_mult__DOT__part_comb;
        VlUnpacked<QData/*35:0*/, 2> bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_lin_approx__DOT__gen_split_mult__DOT__part_reg;
    };
    struct {
        VlUnpacked<QData/*41:0*/, 128> bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_lin_approx__DOT__u_coeff_rom__DOT__rom;
        VlUnpacked<CData/*1:0*/, 2> bf16_expe_equiv_top__DOT__u_lut__DOT__eo_delay;
        VlUnpacked<SData/*15:0*/, 2176> bf16_expe_equiv_top__DOT__u_lut__DOT__u_rom__DOT__rom;
        VlUnpacked<SData/*15:0*/, 12> bf16_expe_equiv_top__DOT__u_lut__DOT__u_pipe_pad__DOT__gen_delay__DOT__chain;
        VlUnpacked<SData/*15:0*/, 1024> bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_dense_rom__DOT__rom;
        VlUnpacked<SData/*15:0*/, 12> bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_pipe_pad__DOT__gen_delay__DOT__chain;
        VlUnpacked<CData/*3:0*/, 256> bf16_expe_equiv_top__DOT__u_cut__DOT__u_cand_rom__DOT__rom;
        VlUnpacked<CData/*6:0*/, 11> bf16_expe_equiv_top__DOT__u_cut__DOT__u_tail_rom__DOT__rom;
        VlUnpacked<SData/*12:0*/, 128> bf16_expe_equiv_top__DOT__u_cut__DOT__u_cut_rom__DOT__rom;
        VlUnpacked<SData/*15:0*/, 9> bf16_expe_equiv_top__DOT__u_cut__DOT__u_pipe_pad__DOT__gen_delay__DOT__chain;
        VlUnpacked<CData/*1:0*/, 9> bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo;
        VlUnpacked<CData/*1:0*/, 9> bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route;
        VlUnpacked<SData/*8:0*/, 9> bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int;
        VlUnpacked<CData/*6:0*/, 9> bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail;
        VlUnpacked<IData/*16:0*/, 9> bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac;
        VlUnpacked<CData/*6:0*/, 11> bf16_expe_equiv_top__DOT__u_poly4__DOT__u_tail_rom__DOT__rom;
        VlUnpacked<SData/*15:0*/, 3> bf16_expe_equiv_top__DOT__u_poly4__DOT__u_pipe_pad__DOT__gen_delay__DOT__chain;
        VlUnpacked<CData/*1:0*/, 9> bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo;
        VlUnpacked<CData/*1:0*/, 9> bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route;
        VlUnpacked<SData/*8:0*/, 9> bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int;
        VlUnpacked<CData/*6:0*/, 9> bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail;
        VlUnpacked<IData/*16:0*/, 9> bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac;
        VlUnpacked<CData/*6:0*/, 11> bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__u_tail_rom__DOT__rom;
        VlUnpacked<SData/*15:0*/, 3> bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__u_pipe_pad__DOT__gen_delay__DOT__chain;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vbf16_expe_equiv_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vbf16_expe_equiv_top___024root(Vbf16_expe_equiv_top__Syms* symsp, const char* v__name);
    ~Vbf16_expe_equiv_top___024root();
    VL_UNCOPYABLE(Vbf16_expe_equiv_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
