// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vbf16_expe_equiv_top.h for the primary calling header

#ifndef VERILATED_VBF16_EXPE_EQUIV_TOP___024ROOT_H_
#define VERILATED_VBF16_EXPE_EQUIV_TOP___024ROOT_H_  // guard

#include "verilated.h"


class Vbf16_expe_equiv_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vbf16_expe_equiv_top___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(s_axis_tvalid,0,0);
        VL_OUT8(s_axis_tready,0,0);
        VL_IN8(m_axis_tready,0,0);
        VL_OUT8(o_exp2_tvalid,0,0);
        VL_OUT8(o_exp2_tready,0,0);
        VL_OUT8(o_exp2opt_tvalid,0,0);
        VL_OUT8(o_exp2opt_tready,0,0);
        VL_OUT8(o_lut_tvalid,0,0);
        VL_OUT8(o_lut_tready,0,0);
        VL_OUT8(o_hybrid_tvalid,0,0);
        VL_OUT8(o_hybrid_tready,0,0);
        VL_OUT8(o_cut_tvalid,0,0);
        VL_OUT8(o_cut_tready,0,0);
        VL_OUT8(o_poly4_tvalid,0,0);
        VL_OUT8(o_poly4_tready,0,0);
        VL_OUT8(o_poly4dsp_tvalid,0,0);
        VL_OUT8(o_poly4dsp_tready,0,0);
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s2_eo_code;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s3_base2;
        CData/*7:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s3_mant_src;
        CData/*7:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__gen_axi_pipelined__DOT__vld_sr;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_decompose__DOT__hidden_bit_comb;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s2_eo_code;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s3_base2;
        CData/*7:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s3_mant_src;
        CData/*7:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__gen_axi_pipelined__DOT__vld_sr;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_decompose__DOT__hidden_bit_comb;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__s2_eo_code;
        CData/*7:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__gen_axi_pipelined__DOT__vld_sr;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__u_decompose__DOT__hidden_bit_comb;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s2_eo_code;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s2_route;
        CData/*2:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s2_sparse_exp_index;
        CData/*6:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s2_mantissa;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s3_eo_code;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s3_route;
        CData/*7:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__gen_axi_pipelined__DOT__valid_sr;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_decompose__DOT__hidden_bit_comb;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s2_eo_code;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s2_route;
        CData/*3:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s2_tail_addr;
        CData/*3:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s3_cand_dev;
        CData/*6:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s3_tail_data;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s3_eo_code;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s3_route;
        CData/*7:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__gen_axi_pipelined__DOT__valid_sr;
        CData/*3:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__u_decompose__DOT__status_comb;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__u_decompose__DOT__hidden_bit_comb;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__s2_route;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__s2_eo;
        CData/*3:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__s2_tail_addr;
        CData/*7:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__gen_axi_pipelined__DOT__valid_sr;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__u_decompose__DOT__hidden_bit_comb;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__s2_route;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__s2_eo;
        CData/*3:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__s2_tail_addr;
        CData/*7:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_axi_pipelined__DOT__valid_sr;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_frontend_dsp__DOT__fe1_route;
        CData/*3:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_frontend_dsp__DOT__fe1_tail;
        CData/*1:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_frontend_dsp__DOT__fe1_eo;
        CData/*0:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__u_decompose__DOT__hidden_bit_comb;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v0;
    };
    struct {
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v0;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v0;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v0;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v1;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v1;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v1;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v2;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v2;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v2;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo__v3;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v3;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v3;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v0;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v0;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v0;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v0;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v1;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v1;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v1;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v1;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v2;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v2;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v2;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v2;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo__v3;
        CData/*1:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v3;
        CData/*6:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail__v3;
        CData/*0:0*/ __Vdlyvset__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v3;
        CData/*0:0*/ __VstlFirstIteration;
    };
    struct {
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_n__0;
        CData/*0:0*/ __VactContinue;
        VL_IN16(s_axis_tdata,15,0);
        VL_OUT16(o_exp2_tdata,15,0);
        VL_OUT16(o_exp2opt_tdata,15,0);
        VL_OUT16(o_lut_tdata,15,0);
        VL_OUT16(o_hybrid_tdata,15,0);
        VL_OUT16(o_cut_tdata,15,0);
        VL_OUT16(o_poly4_tdata,15,0);
        VL_OUT16(o_poly4dsp_tdata,15,0);
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s4_exponent;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s5_int_part;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s6_int_part;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s4_int_part;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s6_poly_exp;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__bf16_out;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_normalize__DOT__msb_idx_comb;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_recompose__DOT__bf16_comb;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s4_exponent;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s5_int_part;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s6_int_part;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s4_int_part;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s6_poly_exp;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__bf16_out;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_normalize__DOT__msb_idx_comb;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_recompose__DOT__bf16_comb;
        SData/*11:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__s2_addr;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__s3_rom_data;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__core_data;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__1__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__2__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__3__KET____DOT__nxt;
        SData/*9:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s2_dense_addr;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s3_sparse_data;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s3_dense_data;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__core_data;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_sparse__DOT__data_comb;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__1__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__2__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__3__KET____DOT__nxt;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s2_int_part;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s2_frac;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s3_int_part;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s3_frac;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__ladder_count;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__core_data;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__1__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__2__KET____DOT__nxt;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__u_pipe_pad__DOT__gen_delay__DOT__gen_stage__BRA__3__KET____DOT__nxt;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__s2_int_part;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__core_data;
        SData/*8:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__s2_int_part;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__core_data;
        SData/*15:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_frontend_dsp__DOT__fe1_onehot;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v0;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v1;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v2;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int__v3;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v0;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v1;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v2;
        SData/*8:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int__v3;
    };
    struct {
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s1_decomposed;
        IData/*30:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s3_mant_out;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s7_rounded_fp;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s8_final_fp;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_round__DOT__rounded_comb;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s1_decomposed;
        IData/*30:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s3_mant_out;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s7_rounded_fp;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s8_final_fp;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_round__DOT__rounded_comb;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_lut__DOT__s1_decomposed;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_hybrid__DOT__s1_decomposed;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT__s1_decomposed;
        IData/*31:0*/ bf16_expe_equiv_top__DOT__u_cut__DOT____VdfgTmp_hff4b4fa8__0;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__s1_decomposed;
        IData/*16:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT__s2_frac;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT____Vcellout__gen_horner__BRA__0__KET____DOT__u_step__acc_out;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT____Vcellout__gen_horner__BRA__1__KET____DOT__u_step__acc_out;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT____Vcellout__gen_horner__BRA__2__KET____DOT__u_step__acc_out;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT____Vcellout__gen_horner__BRA__3__KET____DOT__u_step__acc_out;
        IData/*31:0*/ bf16_expe_equiv_top__DOT__u_poly4__DOT____VdfgTmp_hfc587e27__0;
        IData/*21:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__s1_decomposed;
        IData/*16:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__s2_frac;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_frontend_dsp__DOT__fe1_t7;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT____Vcellout__gen_horner__BRA__0__KET____DOT__u_step__acc_out;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT____Vcellout__gen_horner__BRA__1__KET____DOT__u_step__acc_out;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT____Vcellout__gen_horner__BRA__2__KET____DOT__u_step__acc_out;
        IData/*24:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT____Vcellout__gen_horner__BRA__3__KET____DOT__u_step__acc_out;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v0;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v1;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v2;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac__v3;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v0;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v1;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v2;
        IData/*16:0*/ __Vdlyvval__bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac__v3;
        IData/*31:0*/ __VactIterCount;
        QData/*37:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s4_frac_part;
        QData/*58:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__s6_norm_mant;
        QData/*46:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_unified_shift__DOT__unified_shifted;
        QData/*41:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_lin_approx__DOT__packed_coeff;
        QData/*37:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_lin_approx__DOT__frac_aligned;
        QData/*58:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_normalize__DOT__poly_mant_comb;
        QData/*58:0*/ bf16_expe_equiv_top__DOT__u_exp2__DOT__u_round__DOT__unnamedblk1__DOT__sticky_mask;
        QData/*37:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s4_frac_part;
        QData/*58:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__s6_norm_mant;
        QData/*46:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_unified_shift__DOT__unified_shifted;
        QData/*41:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_lin_approx__DOT__packed_coeff;
        QData/*37:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_lin_approx__DOT__frac_aligned;
        QData/*58:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_normalize__DOT__poly_mant_comb;
        QData/*58:0*/ bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_round__DOT__unnamedblk1__DOT__sticky_mask;
        QData/*40:0*/ bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__gen_frontend_dsp__DOT__scaled_comb;
        VlUnpacked<CData/*1:0*/, 5> bf16_expe_equiv_top__DOT__u_exp2__DOT__eo_delay;
        VlUnpacked<QData/*41:0*/, 128> bf16_expe_equiv_top__DOT__u_exp2__DOT__u_lin_approx__DOT__u_coeff_rom__DOT__rom;
        VlUnpacked<SData/*15:0*/, 1> bf16_expe_equiv_top__DOT__u_exp2__DOT__u_pipe_pad__DOT__gen_delay__DOT__chain;
        VlUnpacked<CData/*1:0*/, 5> bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__eo_delay;
        VlUnpacked<QData/*41:0*/, 128> bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_lin_approx__DOT__u_coeff_rom__DOT__rom;
        VlUnpacked<SData/*15:0*/, 1> bf16_expe_equiv_top__DOT__u_exp2_opt__DOT__u_pipe_pad__DOT__gen_delay__DOT__chain;
        VlUnpacked<CData/*1:0*/, 2> bf16_expe_equiv_top__DOT__u_lut__DOT__eo_delay;
        VlUnpacked<SData/*15:0*/, 2176> bf16_expe_equiv_top__DOT__u_lut__DOT__u_rom__DOT__rom;
        VlUnpacked<SData/*15:0*/, 4> bf16_expe_equiv_top__DOT__u_lut__DOT__u_pipe_pad__DOT__gen_delay__DOT__chain;
        VlUnpacked<SData/*15:0*/, 1024> bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_dense_rom__DOT__rom;
        VlUnpacked<SData/*15:0*/, 4> bf16_expe_equiv_top__DOT__u_hybrid__DOT__u_pipe_pad__DOT__gen_delay__DOT__chain;
        VlUnpacked<CData/*3:0*/, 256> bf16_expe_equiv_top__DOT__u_cut__DOT__u_cand_rom__DOT__rom;
    };
    struct {
        VlUnpacked<CData/*6:0*/, 11> bf16_expe_equiv_top__DOT__u_cut__DOT__u_tail_rom__DOT__rom;
        VlUnpacked<SData/*12:0*/, 128> bf16_expe_equiv_top__DOT__u_cut__DOT__u_cut_rom__DOT__rom;
        VlUnpacked<SData/*15:0*/, 4> bf16_expe_equiv_top__DOT__u_cut__DOT__u_pipe_pad__DOT__gen_delay__DOT__chain;
        VlUnpacked<CData/*1:0*/, 5> bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_eo;
        VlUnpacked<CData/*1:0*/, 5> bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_route;
        VlUnpacked<SData/*8:0*/, 5> bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_int;
        VlUnpacked<CData/*6:0*/, 5> bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_tail;
        VlUnpacked<IData/*16:0*/, 5> bf16_expe_equiv_top__DOT__u_poly4__DOT__ctrl_frac;
        VlUnpacked<CData/*6:0*/, 11> bf16_expe_equiv_top__DOT__u_poly4__DOT__u_tail_rom__DOT__rom;
        VlUnpacked<SData/*15:0*/, 1> bf16_expe_equiv_top__DOT__u_poly4__DOT__u_pipe_pad__DOT__gen_delay__DOT__chain;
        VlUnpacked<CData/*1:0*/, 5> bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_eo;
        VlUnpacked<CData/*1:0*/, 5> bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_route;
        VlUnpacked<SData/*8:0*/, 5> bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_int;
        VlUnpacked<CData/*6:0*/, 5> bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_tail;
        VlUnpacked<IData/*16:0*/, 5> bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__ctrl_frac;
        VlUnpacked<CData/*6:0*/, 11> bf16_expe_equiv_top__DOT__u_poly4_dsp__DOT__u_tail_rom__DOT__rom;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vbf16_expe_equiv_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vbf16_expe_equiv_top___024root(Vbf16_expe_equiv_top__Syms* symsp, const char* v__name);
    ~Vbf16_expe_equiv_top___024root();
    VL_UNCOPYABLE(Vbf16_expe_equiv_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
