// AUTO-GENERATED by gen_bf16_expe_cut_tables.cpp -- do not edit.
#ifndef BF16_EXPE_CUT_TABLE_HPP
#define BF16_EXPE_CUT_TABLE_HPP

#include <cstdint>

namespace bf16_expe_cut {

// ---- datapath geometry ----
constexpr int LOG2E_FRAC_BITS = 23;
constexpr uint32_t LOG2E_Q    = 0xB8AA3Bu;  // round(log2(e) * 2^23)
constexpr int FRAC_BITS       = 16;
constexpr int CAND_INDEX_BITS = 8;
constexpr int CAND_COUNT      = 256;
constexpr int CUT_COUNT       = 128;
constexpr int MIN_EXP         = -9;
constexpr int MAX_EXP         = 7;

// ---- storage widths (what actually costs FPGA/ASIC area) ----
constexpr int CUT_DEV_BITS    = 13;
constexpr int CAND_DEV_BITS   = 4;
constexpr int CUT_DEV_BIAS    = -5374;
constexpr int CAND_DEV_BIAS   = -12;
constexpr int PAYLOAD_BITS    = 2765;  // 1664 + 1024 + 77

// ---- subnormal tail ----
constexpr int TAIL_EXP        = 6;
constexpr int TAIL_MANT_LO    = 47;
constexpr int TAIL_MANT_HI    = 57;
constexpr int TAIL_COUNT      = 11;
constexpr int ZERO_EXP        = 6;
constexpr int ZERO_MANT_LO    = 58;

// cut[k] = ((128-k) << (FRAC_BITS-7)) + CUT_DEV_BIAS + cut_dev[k-1]
static const uint16_t cut_dev[CUT_COUNT] = {
    5555, 5329, 5102, 4875, 4729, 4587, 4360, 4129, 3907, 3800, 3565, 3471, 
    3369, 3110, 2908, 2850, 2667, 2521, 2358, 2228, 2170, 2068, 1841, 1751, 
    1673, 1527, 1505, 1322, 1215, 1154, 1063, 1094, 911, 817, 759, 737, 
    699, 657, 511, 489, 387, 360, 447, 241, 219, 197, 175, 120, 
    131, 109, 87, 33, 28, 22, 128, 17, 44, 2, 0, 103, 
    61, 59, 37, 51, 78, 96, 129, 176, 194, 237, 380, 338, 
    352, 366, 489, 466, 513, 640, 638, 696, 718, 841, 879, 942, 
    992, 1042, 1185, 1235, 1282, 1336, 1406, 1501, 1567, 1670, 1772, 1911, 
    1925, 2011, 2112, 2197, 2299, 2402, 2498, 2641, 2737, 2808, 2930, 3027, 
    3170, 3266, 3364, 3499, 3602, 3721, 3841, 3984, 4103, 4223, 4342, 4485, 
    4605, 4736, 4867, 5007, 5141, 5278, 5417, 5558
};

// base[idx] = (128 - (idx >> (CAND_INDEX_BITS-7)))
//             + CAND_DEV_BIAS + cand_dev[idx]
static const uint8_t cand_dev[CAND_COUNT] = {
    11, 11, 11, 10, 11, 10, 10, 10, 10, 9, 10, 9, 9, 8, 9, 8, 9, 8, 8, 8, 8, 7, 8, 7, 
    7, 7, 7, 6, 7, 6, 6, 6, 6, 5, 6, 5, 6, 5, 5, 5, 5, 4, 5, 4, 5, 4, 4, 4, 
    4, 4, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 2, 2, 2, 2, 2, 
    2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 
    1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 
    1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 
    2, 2, 2, 2, 2, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 
    4, 3, 4, 4, 4, 4, 5, 4, 5, 4, 5, 4, 5, 5, 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 
    6, 6, 7, 6, 7, 7, 7, 7, 7, 7, 7, 7, 8, 7, 8, 8, 8, 8, 9, 8, 9, 9, 9, 9, 
    9, 9, 10, 9, 10, 10, 10, 10, 10, 10, 11, 10, 11, 11, 11, 11
};

// BF16 payloads of the subnormal results, mantissa TAIL_MANT_LO..HI
static const uint8_t tail_payload[TAIL_COUNT] = {
    109, 66, 40, 24, 15, 9, 5, 3, 2, 1, 1
};

} // namespace bf16_expe_cut

#endif
