// AUTO-GENERATED by gen_bf16_expe_poly4_tables.cpp -- do not edit.
#ifndef BF16_EXPE_POLY4_TABLE_HPP
#define BF16_EXPE_POLY4_TABLE_HPP

#include <cstdint>

namespace bf16_expe_poly4 {

// ---- datapath geometry ----
constexpr int LOG2E_FRAC_BITS = 23;
constexpr uint32_t LOG2E_Q    = 0xB8AA3Bu;  // round(log2(e) * 2^23)
constexpr int FRAC_BITS       = 17;   // DSP48 B port
constexpr int DEGREE          = 4;
constexpr int COEF_COUNT      = 5;
constexpr int ACC_FRAC        = 22;
constexpr int ACC_W           = 25;   // DSP48 A port
constexpr int COEF_W          = 16;
constexpr int COEF_FRAC       = 14;
constexpr int ROUND_SHIFT     = 15;
constexpr int MIN_EXP         = -9;
constexpr int MAX_EXP         = 7;
constexpr int PAYLOAD_BITS    = 157;  // 80 + 77
constexpr int DSP_SLICES      = 4;   // one per Horner step

// Worst-case distance to a rounding boundary over all inputs,
// in accumulator LSBs (must be >= 0 for bit-exactness).
constexpr int64_t WORST_SLACK = 2;

// ---- subnormal tail ----
constexpr int TAIL_EXP        = 6;
constexpr int TAIL_MANT_LO    = 47;
constexpr int TAIL_MANT_HI    = 57;
constexpr int TAIL_COUNT      = 11;
constexpr int ZERO_EXP        = 6;
constexpr int ZERO_MANT_LO    = 58;

// P(f) = ((((c4*f + c3)*f + c2)*f + c1)*f + c0), coefficients scaled
// by 2^COEF_FRAC.  Ascending order.
static const int32_t coef[COEF_COUNT] = {
    32768,  // c0 = 2.000000000000
    -22711,  // c1 = -1.386169433594
    7850,  // c2 = 0.479125976562
    -1751,  // c3 = -0.106872558594
    228  // c4 = 0.013916015625
};

// BF16 payloads of the subnormal results, mantissa TAIL_MANT_LO..HI
static const uint8_t tail_payload[TAIL_COUNT] = {
    109, 66, 40, 24, 15, 9, 5, 3, 2, 1, 1
};

} // namespace bf16_expe_poly4

#endif
